### ISSUE TITLE
Unable to import name 'clock' from 'time' in cdlib

### ISSUE THREAD

**Issue by Saeedeh-Imani** [GiulioRossetti/cdlib#101]
Hello,
I'm trying to use cdlib and have following error, while running  "from cdlib import algorithms"

ImportError: cannot import name 'clock' from 'time' (unknown location)

I searched and read other same issues and most of them were suggesting to change clock by either time.perf_counter or time.process_time .

Would you please help me how to solve this problem (how/where to change it)? 
I just want to use some overlapping algorithms like angel or bigclam according to your documentation. 

- CDlib version  >>  0.1.8
- Operating System  >> Win 10 - 64-bit
- Python version >>  3.8.2
- Version(s) of CDlib required libraries
>>
python-igraph            0.8.0
angel-cd                 1.0.2
infomap                  1.0.11
(I only could not install leidenalg--had some errors)

----------------------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)
<ipython-input-4-04fbede86098> in <module>
----> 1 from cdlib import algorithms

~\AppData\Local\Programs\Python\Python38\lib\site-packages\cdlib\algorithms\__init__.py in <module>
      1 from .edge_clustering import *
      2 from .crisp_partition import *
----> 3 from .overlapping_partition import *
      4 from .attribute_clustering import *
      5 from .biparitte_clustering import *

~\AppData\Local\Programs\Python\Python38\lib\site-packages\cdlib\algorithms\overlapping_partition.py in <module>
     19 from cdlib.algorithms.internal.LAIS2_nx import LAIS2
     20 from cdlib.algorithms.internal.lfm import LFM_nx
---> 21 from cdlib.algorithms.internal import LEMON
     22 from cdlib.algorithms.internal.SLPA_nx import slpa_nx
     23 from cdlib.algorithms.internal.multicom import MultiCom

~\AppData\Local\Programs\Python\Python38\lib\site-packages\cdlib\algorithms\internal\LEMON.py in <module>
     23 import numpy as np
     24 import math
---> 25 import pulp
     26 from scipy import linalg as splin
     27 import gc

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pulp\__init__.py in <module>
     32 from .constants import VERSION
     33 
---> 34 from .pulp import *
     35 from .amply import *
     36 __doc__ = pulp.__doc__

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pulp\pulp.py in <module>
    100 
    101 from .constants import *
--> 102 from .solvers import *
    103 from collections import Iterable
    104 

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pulp\solvers.py in <module>
     33 import os
     34 import sys
---> 35 from time import clock
     36 from uuid import uuid4
     37 try:

ImportError: cannot import name 'clock' from 'time' (unknown location)
---------------------------------------------------------------------------------------------------

Thanks in advance,

**Comment by GiulioRossetti** [comment]
Hi,
It seems an issue related to the python version. So far cdlib has been tested up to python 3.7: my suggestion is, for now, to create a virtualenv with such python version and use cdlib from there.

Unfortunately, the issue can be tracked to an external import (the pulp library) so we cannot account directly for it.

**Comment by Saeedeh-Imani** [comment]
> Hi,
> It seems an issue related to the python version. So far cdlib has been tested up to python 3.7: my suggestion is, for now, to create a virtualenv with such python version and use cdlib from there.
<
Hello,
Thank you so much for your help. I tried creating a virtualenv  with python 3.7 and it worked properly.
