### ISSUE TITLE
an error named "To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient." will arise when  use the cdlib

### ISSUE THREAD

**Issue by langyayue99** [GiulioRossetti/cdlib#103]
**Describe the bug**

**To Reproduce**
- CDlib version
- Operating System 
- Python version
- Version(s) of CDlib required libraries

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lunaticbg** [comment]
use `pip install python-igraph` instead of `pip install igraph`
