### ISSUE TITLE
I have a issues

### ISSUE THREAD

**Issue by huzhangron** [GiulioRossetti/cdlib#105]
when i runing 

from cdlib.algorithms import louvain
import networkx as nx
g = nx.karate_club_graph()
communities = louvain(g)
mod = communities.adjusted_mutual_information([[1,2],[3,4]])

 nodes_second = {node: None for community in second_partition.communities for node in community}
AttributeError: 'list' object has no attribute 'communities'

**Comment by GiulioRossetti** [comment]
What is second_partition in your code?
I don't see it declared before it's usage.

It seems that such variable contains just a list not an object returned by the library.

**Comment by huzhangron** [comment]
Sorry, Let me redescribe the error：

from cdlib.algorithms import louvain
import networkx as nx
g = nx.karate_club_graph()
communities = louvain(g)
mod = communities.adjusted_mutual_information([[1,2],[3,4]])

I got an error when I ran the above codes as follow:

Traceback (most recent call last):
  File "D:/conda/Project/Matplotlib/Socail_networkx/Cdlib-动态社区库/cdlib_test.py", line 5, in <module>
    mod = communities.adjusted_mutual_information([[1,2],[3,4]])
  File "D:\conda\lib\site-packages\cdlib\classes\node_clustering.py", line 756, in adjusted_mutual_information
    return evaluation.adjusted_mutual_information(self, clustering)
  File "D:\conda\lib\site-packages\cdlib\evaluation\comparison.py", line 327, in adjusted_mutual_information
    __check_partition_coverage(first_partition, second_partition)
  File "D:\conda\lib\site-packages\cdlib\evaluation\comparison.py", line 20, in __check_partition_coverage
    nodes_second = {node: None for community in second_partition.communities for node in community}
AttributeError: 'list' object has no attribute 'communities'


the second_partition is a Argument from the original   __check_partition_coverage function——cdlib\evaluation\comparison.py

**Comment by GiulioRossetti** [comment]
Ok, this clarify everything, thanks.

The argument of adjusted_mutual_information must be a clustering object as well, not a list.

Just apply another algorithm to the same graph and use its result for the comparison.

**Comment by scootermorris** [comment]
I think this means you have an error in your documentation.  In the documentation for NodeClustering it provides the code snippet

`from cdlib.algorithms import louvain, leiden
import networkx as nx
g = nx.karate_club_graph()
communities = louvain(g)
mod = communities.adjusted_mutual_information([[1,2],[3,4]])`
as an example.  If you change the example to:
`from cdlib.algorithms import louvain
import networkx as nx
g = nx.karate_club_graph()
communities = louvain(g)
communities2 = leiden(g)
mod = communities.adjusted_mutual_information(communities2)`
everything works
