### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by mbdjalal** [GiulioRossetti/cdlib#106]
1) I think that you have an error in your formula :
internal_edge_density = ec/(ns*(ns-1))/2.

2) Also, in the formula that calculates the z_modularity

fitness.py (line : 709) :

for node in c:
    dc += c.degree(node)

I think that the correct dc is calculated by graph.degree(node) instead of c.degree(node)

**Comment by Yquetzal** [comment]
Thank for your comment and sorry for the slow answer we were quite busy with the covid situation. 
I'm not sure to understand the problem, could you be more specific ? Both scores works for me, for the z_modularity it might be a problem of networkx version, could you check if your version is up-to-date ? for internal_edge_density do you mean that the formula is wrong ?

**Comment by GiulioRossetti** [comment]
Thanks for the issue.

-The z-modularity score has been fixed in the master branch 

 Regarding internal_edge_density the implementation is coherent with the one reported in 

```
Yang, Jaewon, and Jure Leskovec. 
"Defining and evaluating network communities based on ground-truth." 
Knowledge and Information Systems 42.1 (2015): 181-213.
```
Where mc identify the cardinality of community edge set. I assume that the only issue you have is in the notation (mc instead of ec) since the formula is exactly the same.

**Comment by mbdjalal** [comment]
Dear Rossetti,
Thanks for your efforts,
The formula is correct, <<internal_edge_density = ec/(ns*(ns-1))/2>>, but parentheses are needed <<internal_edge_density = ( ec/(ns*(ns-1)) ) /2 >>.
Djalal MERAD BOUDIA

    Le vendredi 5 juin 2020 à 06:57:45 UTC+1, Giulio Rossetti <notifications@github.com> a écrit :  
 
 


Thanks for the issue.

-The z-modularity score has been fixed in the master branch

Regarding internal_edge_density the implementation is coherent with the one reported in
Yang, Jaewon, and Jure Leskovec. 
"Defining and evaluating network communities based on ground-truth." 
Knowledge and Information Systems 42.1 (2015): 181-213.

Where mc identify the cardinality of community edge set. I assume that the only issue you have is in the notation (mc instead of ec) since the formula is exactly the same.

**Comment by mbdjalal** [comment]
Dear Rossetti,
EXCUSE ME, here is the correct formula

Thanks for your efforts,
The formula is correct, <<internal_edge_density = ec/(ns*(ns-1))/2>>, but parentheses are needed <<internal_edge_density = ec/ ( (ns*(ns-1))  /2 )>>.
Djalal MERAD BOUDIA

    Le samedi 6 juin 2020 à 11:13:46 UTC+1, djalal merad boudia <mbdjalal@yahoo.fr> a écrit :  
 
  Dear Rossetti,
Thanks for your efforts,
The formula is correct, <<internal_edge_density = ec/(ns*(ns-1))/2>>, but parentheses are needed <<internal_edge_density = ( ec/(ns*(ns-1)) ) /2 >>.
Djalal MERAD BOUDIA

    Le vendredi 5 juin 2020 à 06:57:45 UTC+1, Giulio Rossetti <notifications@github.com> a écrit :  
 
 


Thanks for the issue.

-The z-modularity score has been fixed in the master branch

Regarding internal_edge_density the implementation is coherent with the one reported in
Yang, Jaewon, and Jure Leskovec. 
"Defining and evaluating network communities based on ground-truth." 
Knowledge and Information Systems 42.1 (2015): 181-213.

Where mc identify the cardinality of community edge set. I assume that the only issue you have is in the notation (mc instead of ec) since the formula is exactly the same.

**Comment by GiulioRossetti** [comment]
The issue was in an external package. 
It has been fixed, reinstall the CDlib dependencies.

**Comment by mbdjalal** [comment]
Ok, thanks

    Le samedi 6 juin 2020 à 12:04:13 UTC+1, Giulio Rossetti <notifications@github.com> a écrit :  
 
 


The issue was in an external package.
It has been fixed, reinstall the CDlib dependencies.
