### ISSUE TITLE
infomap

### ISSUE THREAD

**Issue by seemarani1307** [GiulioRossetti/cdlib#110]
Hello,

I am new to network science. when i run this code
 
from cdlib import algorithms
import networkx as nx
G = nx.karate_club_graph()
coms = algorithms.infomap(G)

 i am getting the following error

**TypeError: 'Network' object is not callable**

Please check.

Thanks

**Comment by GiulioRossetti** [comment]
Could you please provide the full stacktrace for the error? 

At first sight the code you posted seems correct and should not raise that kind of error.

**Comment by Yquetzal** [comment]
I checked qucikly and the problem seems to be that cdlib installed by pip is not up-to-date with the code on github. 
You should install cdlib using pip install git+https://github.com/GiulioRossetti/cdlib.git
to get the latest version and it should work

**Comment by GiulioRossetti** [comment]
Most importantly, have you checked if the infomap python package is installed? It is an optional dependency for CDlib, if it is missing the selected algorithm cannot be executed.

**Comment by Yquetzal** [comment]
@GiulioRossetti I reproduced the problem with a clean install on a google colab, see my previous message

**Comment by GiulioRossetti** [comment]
@Yquetzal ok, it should be a regression issue due to changes in the infomap version: the cdlib version available with pip still requires an early beta version of such library while the one on GitHub supports its latest stable one.

**Comment by seemarani1307** [comment]
TypeError                                 Traceback (most recent call last)
<ipython-input-13-708ce8ba7a09> in <module>()
      2 import networkx as nx
      3 G = nx.karate_club_graph()
----> 4 coms = algorithms.infomap(G)

/usr/local/lib/python3.6/dist-packages/cdlib/algorithms/crisp_partition.py in infomap(g)
    683     with pipes():
    684         im = imp.Infomap()
--> 685         network = im.network()
    686         for e in g1.edges():
    687             network.addLink(e[0], e[1])

TypeError: 'Network' object is not callable

**Comment by seemarani1307** [comment]
Hello Sir,

Thanks for your kind reply. I have posted. Please check.

Thanks

**Comment by Yquetzal** [comment]
So, could you try to uninstall cdlib, and reinstall it using this command:
pip install git+https://github.com/GiulioRossetti/cdlib.git
It should solve the problem

**Comment by seemarani1307** [comment]
I just tried it. But its showing same error.

**Comment by Yquetzal** [comment]
Have you tried to restart your session if you're in a notebook ? 
The current code for the infomap function that you can check on github (I paste it below) is different from the one that appear in your code, so it necessarily means that you do not have the latest version of cdlib

`with pipes():
        im = imp.Infomap()
        for e in g1.edges():
            im.addLink(e[0], e[1])
        im.run()`

**Comment by seemarani1307** [comment]
Its working sir.

Thank you  very much. :)

**Comment by seemarani1307** [comment]
I uninstalled cdlib and reinstalled using command pip install git+https://github.com/GiulioRossetti/cdlib.git. and its working.
