### ISSUE TITLE
ARI score error

### ISSUE THREAD

**Issue by seemarani1307** [GiulioRossetti/cdlib#111]
Hello Sir,
Please check this.

from cdlib.algorithms import louvain
g = nx.karate_club_graph()
communities = louvain(g)
mod = communities.adjusted_rand_index([[1,2], [3,4]])
mod

gives this error

AttributeError                            Traceback (most recent call last)
<ipython-input-10-2e2a59ea8e40> in <module>()
      2 g = nx.karate_club_graph()
      3 communities = louvain(g)
----> 4 mod = communities.adjusted_rand_index([[1,2], [3,4]])
      5 mod

2 frames
/usr/local/lib/python3.6/dist-packages/cdlib/evaluation/comparison.py in __check_partition_coverage(first_partition, second_partition)
     18 def __check_partition_coverage(first_partition, second_partition):
     19     nodes_first = {node: None for community in first_partition.communities for node in community}
---> 20     nodes_second = {node: None for community in second_partition.communities for node in community}
     21 
     22     if len(set(nodes_first.keys()) ^ set(nodes_second.keys())) != 0:

AttributeError: 'list' object has no attribute 'communities'

Thanks & Regards,
Seema Rani

**Comment by GiulioRossetti** [comment]
The error is a correct behavior: the adjusted_rand_index requires a community object as input, not a list of lists. 

Check the examples in the online documentation.
