### ISSUE TITLE
there is a bug about graph attribute

### ISSUE THREAD

**Issue by langyayue99** [GiulioRossetti/cdlib#112]
**Describe the bug**
when I use the overlapping community detection algorithm 'LFM',there will be a error named'Graph' object has no attribute 'node'.I tried upgrade the cdlib ,but  it didn't work.I think the networks didn't support the graph attribute node and it's has been changed to attribute nodes.likely g.nodes() not g.node().Maybe you can check it .

**Expected behavior**
check the graph attribute nodes in networkx

**Comment by GiulioRossetti** [comment]
Please provide a minimal code example along with the complete error stacktrace  you obtain so to allow us reproducing the error.

**Comment by langyayue99** [comment]
this is the example:

from cdlib import algorithms
import igraph
import networkx as nx
G = nx.karate_club_graph()
lfm = algorithms.lfm(G, alpha=0.8)

 and it cause a error ,I have checked  the networkx version is  2.4 :

last)<ipython-input-22-46ab046f7e1a> in <module>
      3 import networkx as nx
      4 G = nx.karate_club_graph()
----> 5 lfm = algorithms.lfm(G, alpha=0.8)
~/external-libraries/cdlib/algorithms/overlapping_partition.py in lfm(g, alpha)
    294 
    295     algorithm = LFM_nx(g, alpha)
--> 296     coms = algorithm.execute()
    297 
    298     return NodeClustering(coms, g, "LFM", method_parameters={"alpha": alpha}, overlap=True)
~/external-libraries/cdlib/algorithms/internal/lfm.py in execute(self)
     83     def execute(self):
     84         communities = []
---> 85         node_not_include = list(self.g.node.keys())[:]
     86         while len(node_not_include) != 0:
     87             c = Community(self.g, self.alpha)
AttributeError: 'Graph' object has no attribute 'node'

**Comment by GiulioRossetti** [comment]
Thanks you, I'll check into it asap.

**Comment by GiulioRossetti** [comment]
The bug affects only the packaged version of the library: please, install CDlib from the master branch of the repository to temporarily solve it.

The fix will be included in the next packaged release.
