### ISSUE TITLE
scores computation request

### ISSUE THREAD

**Issue by seemarani1307** [GiulioRossetti/cdlib#117]
Hello Sir,

Please help in finding z-score, density, separability, cohesiveness, and clustering coefficient as explained in paper **https://link.springer.com/content/pdf/10.1007/s10115-013-0693-z.pdf**

Thanks & Regards

**Comment by GiulioRossetti** [comment]
Hi, have you checked the library documentation for the fitness functions? 

Some of the measures you specified are already implemented in cdlib.

**Comment by seemarani1307** [comment]
Hello Sir,

ok sir. I will check.

Thanks & Regards

**Comment by seemarani1307** [comment]
Hello Sir,

how can we conclude which community detection algorithms is performing better on the basis of scoring functions?
Also how partition comparison can be used for ground truth testing as i am not having ground truth for community.
I am new to this community detection. Please help.

Thanks & Regards,
Seema

**Comment by GiulioRossetti** [comment]
Hi,
since community discovery is an ill posed problem you cannot conclude that a method is the best one on your dataset (there's no free lunch unfortunately). What you can do is to observe that wrt a given scoring function a given method perform better than others (changing the scoring function such ranking may not hold).

Regarding partition comparison: if you don't have a ground truth you can at most compare different node clustering and assess how much they are similar with each other.

**Comment by seemarani1307** [comment]
Hello Sir,

Thank you very much sir.

**Comment by seemarani1307** [comment]
Hello Sir,
can we compute precision, recall using cdlib for ground truth testing?
Thanks & Regards

**Comment by GiulioRossetti** [comment]
Hi,
Give a look to the NF1 scoring function for partition comparisons. If you need something more specific give a look to my f1-communities repository on GitHub.

**Comment by seemarani1307** [comment]
Hello Sir,

it will calculate f1 score which is harmonic mean of precision and recall. but if we want to calculate precision and recall individually? Like in this example in cdlib document.

from cdlib import evaluation, algorithms
 g = nx.karate_club_graph()
louvain_communities = algorithms.louvain(g)
leiden_communities = algorithms.leiden(g)
evaluation.f1(louvain_communities,leiden_communities)

**Comment by GiulioRossetti** [comment]
Give a look at: https://github.com/GiulioRossetti/f1-communities it implements what you need.

**Comment by seemarani1307** [comment]
Thankyou very much sir

**Comment by seemarani1307** [comment]
Hello Sir,


How Maximum-ODF (Out Degree Fraction)  and Average-ODF signifies better community score? Like value of maximum-odf should be low or high for better community structure? what should be value of Average-ODF for better commuity strcuture (low or high)?

Thanks and Regards,
Seema

**Comment by GiulioRossetti** [comment]
They are proxies for community separability: the lower, the better.

The idea is to minimize the fraction of edges that cross community boundaries. Taking the maximum you are looking at the worst case scenario (thus comparing different partition can be seen as a minmax problem).

**Comment by seemarani1307** [comment]
Hello Sir,

Thank you very much.

Regards,
Seema Rani
