### ISSUE TITLE
label propagation algorithm

### ISSUE THREAD

**Issue by mary199417** [GiulioRossetti/cdlib#122]
hello
I want to use a label propagation algorithm. This algorithm is random that in each run the result is different. I run the algorithm multi-time but the result and communities are the same.

import networkx as nx
from cdlib import algorithms

g = nx.karate_club_graph()
coms = algorithms.label_propagation(g)
community = coms.to_node_community_map()
print(community)

________________________________________________________
also, I want to evaluate nmi metric for this result. nmi metric just uses nodeCluster object. I want to compare the result of the algorithm with a True label that is a list but it returns an error. how can I use nmi?

from cdlib import evaluation, algorithms

g = nx.karate_club_graph()
coms = algorithms.label_propagation(g)
community = coms.to_node_community_map()
NMI = evaluation.normalized_mutual_information(TrueLabel,coms)

**Comment by GiulioRossetti** [comment]
Hi,
I'll try to answer to both your questions:

1) indeed, the classic LP algorithm has a stochastic definition: cdlib inherit its  implementation from networkx, I suggest you to check it for more details on such behavior. 

2) you have to provide the true labels as clustering objects as well. Basically, create the clustering description as a list of lists of nodes (e.g. communities) then assign it to the clustering field of an empty Clustering object.

**Comment by mary199417** [comment]
Thanks for your response.
for provide the true labels as a NodeClustering object first I create a list of communites as below.
community = [ [0,1,2,3,4,5,6,7,10,11,12,13,16,17,19,21] , [8,9,14,15,18,20,22,23,24,25,26,27,28,29,30,31,32,33] ]
but I have problem with assign the community list to NodeClustering object. How can I do it?

**Comment by GiulioRossetti** [comment]
You can do it easily as follows:

```
community = [ [0,1,2,3,4,5,6,7,10,11,12,13,16,17,19,21] , [8,9,14,15,18,20,22,23,24,25,26,27,28,29,30,31,32,33] ]
nc = NodeClustering(community, None, "Ground-Truth", method_parameters={"": ""})
```

If you like, you can pass as second argument the graph instead of None so to be able to compute statistics also for the ground truth partition.
