### ISSUE TITLE
Extracting communities and node names as vectors

### ISSUE THREAD

**Issue by hkarakurt** [GiulioRossetti/cdlib#123]
Hello,
I used Louvain algorithm on a network (1299 nodes) and cdLib works perfect. I did clustering evalution. I am planning to do the same on a bigger network (about 15000 nodes).

Is it possible to extract clustering results as a 2 column file with one column as node name (names as given in the graphml file) and other column as the cluster that node belongs?

I am relatively new to Python so I could not achieve it. Does cdLib have a function like this?

Thank you in advance

**Comment by Yquetzal** [comment]
Hi,
If I understand correctly your question, what you want correspond to the `to_node_community_map()` function. You can find it in the documentaiton there: https://cdlib.readthedocs.io/en/latest/reference/classes/node_clustering.html#cdlib.NodeClustering.to_node_community_map
it yields a dictionary, if you want a file, you can write it the old-school way: https://www.tutorialspoint.com/How-to-save-a-Python-Dictionary-to-CSV-file
Or more conveniently use for instance the pandas package, first creating a dataframe using from_dict
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_dict.html
and then writing it using write_csv
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html

**Comment by hkarakurt** [comment]
Thank you for your answer. Actually my main problem is, the graph (in graphml format) I use have node names as gene symbols such as "ACT2,DHD3 etc.". When I use to_node_community_map() function, I have the keys and the clusters they belong. How can I match those keys and real node names?

I am sorry if it is a really basic question, I am really new to Python. 

Thank you in advance.

**Comment by Yquetzal** [comment]
Is it possible to share the network, so that I can try ? In theory, it should give you the node names and not the keys, so I don't know if it is an unexpected behavior or if it is just due to your input data. I remember that graphml might have both an ID and a name for nodes, and when you load the file, maybe it loads the IDs as what we call names, and the name is just present as a "label". In which case you can for instance replace node IDs by those names with networkx relabel_nodes function, for instance.

**Comment by hkarakurt** [comment]
Thank you again. You can download my network here [https://drive.google.com/file/d/1OtJbxlsG2ahGc8b3qA8X-5qfTDql84f3/view?usp=sharing](url)

Actually it has both IDs and node names. When I open it in Notepad it looks like this:
 <node id="n0">
      <data key="v_name">CTDNEP1</data>
    </node>
    <node id="n1">
      <data key="v_name">CNEP1R1</data>
    </node>
    <node id="n2">
      <data key="v_name">BCKDHA</data>
    </node>

Thank you in advance

**Comment by Yquetzal** [comment]
I could not load your graph because I need an authorisation, but I wrote a minimal example with another .graphml file, I think it is the same situation.
You can check here: 
https://colab.research.google.com/drive/1ih29gFdxgkwAJPp9W-IJlYP9DZXMHOVB?usp=sharing

**Comment by hkarakurt** [comment]
Thank you so much. Relabelling worked. I just prepared my library when I constructed my network but using your codes are also working.
