### ISSUE TITLE
How to save a graph/plot, with respect to Network Clusters and Community Graph, in png/jpg format

### ISSUE THREAD

**Issue by sumitpowar** [GiulioRossetti/cdlib#124]
Hi,

I want to save the plots generated using following functions:

**plot_network_clusters(graph, partition, position, figsize=(8, 8), node_size=200, plot_overlaps=False, plot_labels=False)

plot_community_graph(graph, partition, figsize=(8, 8), node_size=200, plot_overlaps=False, plot_labels=False)**

Please provide a feature to do the same.

**Comment by GiulioRossetti** [comment]
Hi,
they are all matplotlib objects. To save them on file just

```
import matplotlib.pyplot as plt

# some code to get the partition...

viz.plot_network_clusters(graph, partition, position, figsize=(8, 8), node_size=200, plot_overlaps=False, plot_labels=False)

plt.savefig("figure.pdf")
```
