### ISSUE TITLE
Python 3.8 error within required pulp library because of cdlib's requirement to use an outdated version of pulp

### ISSUE THREAD

**Issue by redhairedcelt** [GiulioRossetti/cdlib#125]
**Describe the bug**
It seems cdlib requires only pulp version 1.6.  However in Python 3.8, a function used in pulp is depreciated. A function calls "from time import clock" which is now depreciated in Python 3.8.  Pulp has fixed the problem in recent versions (in particular 2.2, the most recent), but running "from cdlib import algorithms" causes an error when pulp tries to use the depreciated "clock" function.  my solution was to manually download a new version of pulp (2.2), which generated a warning from pip that I created a conflict with cdlib, which requires 1.6.  However, I was then able to run "from cdlib import algorithms" without issue.

**To Reproduce**
- CDlib version
0.1.8 
- Operating System 
MacOs Catalina
- Python version
3.8
- Version(s) of CDlib required libraries
pulp 1.6 vs pulp 2.2

**Expected behavior**

**Screenshots**
ERROR: cdlib 0.1.8 has requirement pulp==1.6.*, but you'll have pulp 2.2 which is incompatible.

**Additional context**
Please let me know if I can help troubleshoot anymore.  I am really excited about cdlib and can't wait to start using it in projects.  Thanks for all your hard work on this package!

**Comment by GiulioRossetti** [comment]
The issue was previously raised and addressed in the master branch of the repository. 

We'll release an updated packages version of cdlib within the end of them month.

**Comment by Yquetzal** [comment]
For now you can install cdlib directly from github with
pip install git+https://github.com/GiulioRossetti/cdlib.git

**Comment by redhairedcelt** [comment]
Thanks for the speedy response and apologies for raising a duplicate issue.  Thanks again for an amazing package; I've been experimenting with it all day!
