### ISSUE TITLE
Duration difference between MCL in cdLib, reference library and markov-clustering library

### ISSUE THREAD

**Issue by hkarakurt** [GiulioRossetti/cdlib#126]
Hello,
I am so sorry if my question is inappropriate. I want to use MCL to cluster my network (about 17000 nodes), but kernel crashes everytime (I have 16 GB RAM).
Another library that does MCL clustering (markov-clustering library). I believe the difference comes from the adjacency matrix formats. That library works but I cannot import the results as cdLib NodeClustering object to do some comparisons such as ARI.

Is there any way to complete this task? Is it possible to import another clustering result directly to cdLib?

Thank you in advance

**Comment by Yquetzal** [comment]
So the library that works is this one ? https://github.com/HarshHarwani/markov-clustering-for-graphs
In theory we should use the same implementation, so there might be a problem in the way the code is integrated. Can you share the graph on which it is not working so that we can make it work ? 

You can also import the resulting clustering in CDlib by creating your own instance of clustering object:

`NodeClustering(communities, graph, method_name, method_parameters=None, overlap=False)`
from https://cdlib.readthedocs.io/en/latest/reference/classes/node_clustering.html

@GiulioRossetti We have several questions on this problem, I propose to add a small tutorial in the documentation, in the node clustering part, to explain how to create a clustering object from custom formats. Any recommendation ?

**Comment by hkarakurt** [comment]
Thank you for your answer.
Yes this is the library.
The graph is the same that I shared before in another question. Link is here:
https://drive.google.com/file/d/1OtJbxlsG2ahGc8b3qA8X-5qfTDql84f3/view?usp=sharing

As I understand, markov-clustering library clusters are in list of tuples (I think it is different than cdLib NodeClustering object's communities section) format, and the sparse matrix of numpy it uses cannot use rownames so the result involves only the indices of nodes. 

Thank you in advance

**Comment by Yquetzal** [comment]
I checked the code, but I don't understand why the library you mentioned should work and ours not. I checked line by line and the memory error arises when doing `np.linalg.matrix_power(matrix, 2)`. This takes too much memory. 
I see that the library you mention needs some change to work on your own data, did you change something important? Did you switch to sparse matrices for instance?

**Comment by hkarakurt** [comment]
Hello again,
I am so sorry that I misunderstood your previous post. Actually the working library is this one: https://github.com/GuyAllard/markov_clustering

For 17000 nodes both cdLib and "markov-clustering-for-graphs" libraries are crashing because of memory.

**Comment by GiulioRossetti** [comment]
@Yquetzal & @hkarakurt: I substituted the implementation of MCL in the master branch with the one suggested. 
All tests seem to work: please, provide your feedback.

**Comment by hkarakurt** [comment]
I removed and reinstalled cdLib with "pip install cdlib" command. It is not working. Actually it looks like it works but does not create the results variable and removes the library from kernel. After I try with:
"mcl_communities = algorithms.markov_clustering(g), it does the job but when I type "mcl_communities" it says that variable does not exitst. 
After that I try Louvain clustering and Python could not find "algorithms". It is like I have never imported package.

I tried "pip install git://github.com/GiulioRossetti/cdlib.git" command but I had error. I think I suppose to install it. Error I have:

`ERROR: Exception:
Traceback (most recent call last):
  File "/home/huk/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/huk/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/home/huk/anaconda3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/huk/anaconda3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/huk/anaconda3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/huk/anaconda3/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "/home/huk/anaconda3/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 273, in unpack_url
    unpack_vcs_link(link, location)
  File "/home/huk/anaconda3/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 103, in unpack_vcs_link
    vcs_backend.unpack(location, url=hide_url(link.url))
  File "/home/huk/anaconda3/lib/python3.7/site-packages/pip/_internal/vcs/versioncontrol.py", line 618, in unpack
    self.obtain(location, url=url)
  File "/home/huk/anaconda3/lib/python3.7/site-packages/pip/_internal/vcs/versioncontrol.py", line 524, in obtain
    url, rev_options = self.get_url_rev_options(url)
  File "/home/huk/anaconda3/lib/python3.7/site-packages/pip/_internal/vcs/versioncontrol.py", line 444, in get_url_rev_options
    secret_url, rev, user_pass = self.get_url_rev_and_auth(url.secret)
  File "/home/huk/anaconda3/lib/python3.7/site-packages/pip/_internal/vcs/git.py", line 359, in get_url_rev_and_auth
    url, rev, user_pass = super(Git, cls).get_url_rev_and_auth(url)
  File "/home/huk/anaconda3/lib/python3.7/site-packages/pip/_internal/vcs/versioncontrol.py", line 419, in get_url_rev_and_auth
    "e.g. svn+http://myrepo/svn/MyApp#egg=MyApp".format(url)
ValueError: Sorry, 'git://github.com/GiulioRossetti/cdlib.git' is a malformed VCS url. The format is <vcs>+<protocol>://<url>, e.g. svn+http://myrepo/svn/MyApp#egg=MyApp
`

**Comment by GiulioRossetti** [comment]
You are using the wrong syntax for the installation. Try with:

`pip install git+https://github.com/GiulioRossetti/cdlib.git
`

**Comment by hkarakurt** [comment]
Sorry for my mistake,
I installed via pip install git. Function is working but the modularity (newman_girman_modularity) is looking wrong. I used a 1299 node test network with igraph in R and cdLib. A week ago for all community detection algorithms, modularities from R and Python were same. Now they are completely different and modularit from cdLib is really close to zero. Everything else is working fine (to_node_community map, speed etc.)

Also, to import algorithms from cdlib, it now requires to install mosek library so I installed it.

**Comment by GiulioRossetti** [comment]
@hkarakurt I performed a clean install of cdlib in an empty conda environment: I'm not experiencing a missing dependency for mosek. Are you sure this is not due to your current environment? Can you replicate the issue in a clean setting?

Regarding the modularity score: indeed you can expect some fluctuation, however not that big. 
Moreover, that part of the library has not changed recently.
I've made a test on the karate_club graph and I get almost the same value from both cdlib and igraph in R. 
Could you please share your graph to perform further tests?

**Comment by hkarakurt** [comment]
I use Anaconda with Spyder and probably the problem is about my environment because it has many libraries.

The networks I used are here: https://drive.google.com/drive/folders/1P1uZY4Poe0onBPbul4m9jiLzmKQ9KqRS?usp=sharing
I gave you permission to access data in this folder.

Thank you for your support

**Comment by Yquetzal** [comment]
@hkarakurt I corrected a bug in our code, now it should work as expected.
Note that you need to reinstall cdlib using `pip install git+https://github.com/GiulioRossetti/cdlib.git`
@Giulio: by default the order of nodes in the to_scipy_matrix function are the order of nodes according to the function nx.node(), while we were expecting an ordering based on nodes numbers.

**Comment by hkarakurt** [comment]
Thank you for your help and support. Everything works perfect.
