### ISSUE TITLE
How do I increase the maximum number of communities in a graph visualization?

### ISSUE THREAD

**Issue by eternity1984** [GiulioRossetti/cdlib#127]
Hi, May I please ask you two questions in graph visualization?

1. The maximum number of communities is 16 (the same as the number of COLOR elements); is there a reason why it's limited to 16?
2. Do you plan to apply a lighter color to a label if the node is a dark color?
---

**Is your feature request related to a problem? Please describe.**
- I'm stuck with a limited number of communities
- If the node is dark, the label is hard to see

**Describe the solution you'd like**
- I don't want the number of communities to be limited.
-  I'd like to determine the color of the label based on the relative luminance of the node's color.
- I'd like to apply a color map if possible.

**Describe alternatives you've considered**
I've tried to create an [implementation](https://github.com/eternity1984/cdlib/commit/e0c56279967f3681bdee9dbc3caef48095c61054).

**Additional context**

![font color](https://user-images.githubusercontent.com/34591767/90705978-1b28fc80-e2cf-11ea-89db-fd4c0c798b5d.png)

```python
G = nx.karate_club_graph()
coms = algorithms.louvain(G)
pos = nx.spring_layout(G, k=0.3)

# viz.plot_network_clusters(G, coms, pos, plot_overlaps=True, plot_labels=True, cmap=None)
# viz.plot_network_clusters(G, coms, pos, plot_overlaps=True, plot_labels=True, cmap="jet")
viz.plot_network_clusters(G, coms, pos, plot_overlaps=True, plot_labels=True, cmap=plt.cm.Wistia)
```
![image](https://user-images.githubusercontent.com/34591767/90707113-d05cb400-e2d1-11ea-8f47-e9a02e592c8d.png)

**Comment by GiulioRossetti** [comment]
Thanks for the detailed issue and fix proposal.

I agree that such limit does not make sense: it was just a temporary solution to avoid assigning the same color to multiple communities. Moreover, such limit implicitly shows only the 16 bigger communities.

I think your fix for that allows selecting a color palette totally makes sense. Moreover, I was wandering if it could be useful to add another parameter that allows to filter out communities of small sizes (so to avoid wasting colors and limit the information loss).

Regarding the label color based on the node color: I don't know how to get such behavior (or even if it is possible to easily obtain it).

**Comment by eternity1984** [comment]
@GiulioRossetti , I appreciate your prompt reply and great advice.

The color of the label based on relative luminance is already implemented.:smile:

Regarding the relative luminance: the following links is useful:
https://en.wikipedia.org/wiki/Relative_luminance
https://ux.stackexchange.com/questions/107318/formula-for-color-contrast-between-text-and-background

> I was wandering if it could be useful to add another parameter that allows to filter out communities of small sizes (so to avoid wasting colors and limit the information loss).

I really like your idea, but I can't come up with a good algorithms to do it.
I will try to make some. If all goes well, I send a pull request.:wink:

**Comment by GiulioRossetti** [comment]
That's great!
I didn't notice the luminance fix (I only quickly skimmed the code, my fault!) :-)

Filtering out small communities should be trivial: the list that contains them in the CDlib clustering object is already ordered by (decreasing) size.

**Comment by eternity1984** [comment]
Wow💡 Well, is it enough to implement top_k then?

**Comment by GiulioRossetti** [comment]
Yes, either top_k or min_size!

**Comment by eternity1984** [comment]
Thank you! I'll send a pull request later.😄
