### ISSUE TITLE
Implementation of AGDL

### ISSUE THREAD

**Issue by Hungyi5** [GiulioRossetti/cdlib#129]
Hello, I find something strange about the implementation of AGDL algorithm.

The input in the referenced implementation is a data matrix. https://github.com/myungjoon/GDL
```python
def AGDL(data, targetClusterNum, Ks, Kc):
```
Following the paper, they first computed pairwise distance of the input data and convert the pairwise distance to pairwise similarity then construct a k nearest neighbor graph.

The implementation in cdlib/cdlib/algorithms/internal/AGDL.py requires a graph as input for consistency.
```python
def Agdl(g, target_cluster_num, ks, kc, a):
    data = nx.to_numpy_matrix(g)
    distance, indices = __knn(ks, data)
    ...
```
Nevertheless, I thought nx.to_numpy_matrix(g) returns a pairwise similarity matrix of input data (In graph, higher edge weight means closer connection.) with size (n_sample, n_sample) rather than data with size (n_sample, n_features). So it is unnecessary and not suitable to apply NearestNeighbors().fit(x) (in __knn()).

The other thing (not a problem) is __w_matrix does not require data
```python
def __w_matrix(data, distance, indices, ks, a=10):
    ...
    weight_matrix[i][j] = np.exp(-1 * (np.linalg.norm(data[i] - data[j]) ** 2) / sigma2)
```
is equivalent to
```python
weight_matrix[i][j] = np.exp(-1 * (np.linalg.norm(distance[i,j]) ** 2) / sigma2)
```

Willing to discuss further. Thanks.

**Comment by Yquetzal** [comment]
Thanks a lot for raising the point, I'm a little bit overwhelmed with the teaching starting this semester here, but I'll definitively check it next week if Giulio hasn't done it before.

**Comment by GiulioRossetti** [comment]
Hi, sorry I missed this issue. I'll try to look at it as soon as possible.

**Comment by GiulioRossetti** [comment]
@Hungyi5 I see your point.

Basically, (correct me if I'm wrong) we start with an explicit graph while the original implementation builds one starting from (disconnected) data points in a metric space using knn.
If that's the case then it's likely that we'll have to revise part of AGDL code, not only to remove the (useless) knn call.

Do you plan to make such a change yourself and make a pull request, or do you prefer that we take care of it?
I can schedule it but cannot guarantee a quick fix (that's a quite heavy period for me too).

**Comment by Hungyi5** [comment]
Thanks for your reply.

I can start to work on it in the next few days.

**Comment by Hungyi5** [comment]
I am currently working on it but there is something
