### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by beckedorf** [GiulioRossetti/cdlib#130]
Since the last release some features were added and requirements were updated (eg networkx). Do you plan to create a new release?

Thanks

**Comment by GiulioRossetti** [comment]
Hi, yes: I'm completing the integration of an algorithm these days and I will make a new release after completing such task.

**Comment by beckedorf** [comment]
Thanks a lot

**Comment by beckedorf** [comment]
Thanks a lot

**Comment by GiulioRossetti** [comment]
CDlib v0.1.9 ("Almighty Bob") released: https://github.com/GiulioRossetti/cdlib/releases/tag/v0.1.9
