### ISSUE TITLE
ModuleNotFoundError: Optional dependency not satisfied: install package wurlitzer to use infomap

### ISSUE THREAD

**Issue by student2k21** [GiulioRossetti/cdlib#135]
**Describe the bug**  
I am using pycharm IDE and am attempting to use your library's infomap community detection on a directed weighted graph created via networkx but I am getting the error module not found. I installed wurlitzer latest edition and infomap's latest version but it does not work. I installed all packages within PyCharm IDE

**Error**  
Traceback (most recent call last):
  File "C:/A/A/PycharmProjects/A/a.py", line 5, in <module>
    coms = algorithms.infomap(G)
  File "C:\A\A\PycharmProjects\A\venv\lib\site-packages\cdlib\algorithms\crisp_partition.py", line 686, in infomap
    raise ModuleNotFoundError("Optional dependency not satisfied: install package wurlitzer to use infomap.")
ModuleNotFoundError: Optional dependency not satisfied: install package wurlitzer to use infomap.

Code used  
```
from cdlib import algorithms
import networkx as nx
from graphClass import G

coms = algorithms.infomap(G)
print(coms)
```

**To Reproduce**  

- CDlib version 0.1.10
- Operating System Windows 10
- Python version 3.7
- Required libraries installed; infomap, wurlitzer

**Comment by GiulioRossetti** [comment]
Hi,
try installing cdlib in a vanilla env using:

pip install cdlib[C]

in this way, you should be assured to have all the additional dependencies at the optimal version.
Unfortunately, the installation of some 3rd party libraries is troublesome under windows (Infomap being one of them).

**Comment by student2k21** [comment]
@GiulioRossetti thank-you for your prompt response, I will re-install cdlib this way
