### ISSUE TITLE
Question and Possible Discussion regarding Role Discovery as an addition to CDLib

### ISSUE THREAD

**Issue by DonaldTsang** [GiulioRossetti/cdlib#137]
I would like to ask something regarding Role Detection as a derivation of Community Detection:
Is it possible to consider role detection (role discovery, role similarity, role-based similarity), since it seems that research regarding roles are still a bit too new and that most research tends to treat it as a sub-problem of Community Detection?

For reference regarding lists of Role Detection algorithms:
- https://www.semanticscholar.org/paper/Role-Discovery-in-Networks-Rossi-Ahmed/88a64102428784fb409c8fd19ea3885a73768dcc
- https://www.semanticscholar.org/paper/From-Community-to-Role-based-Graph-Embeddings-Rossi-Jin/d1b7943154def1fcdc3431814844514bec0c426b
- https://www.semanticscholar.org/paper/Similarity-Measure-for-Social-Networks-A-Brief-Rawashdeh-Ralescu/c14afaa99d79dc667e383eb6d5250d5f61a2cc14
- https://www.semanticscholar.org/paper/Role-Discovery-in-Graphs-Using-Global-Features%3A-and-Gupte-Ravindran/5357319c3c02ba354f8a821aa546111efe82c165

**Comment by GiulioRossetti** [comment]
Hi, thanks for the very interesting references, I'll give them a proper look as soon as possible.

Indeed, Community Detection and Role Detection are strictly related problems and some approaches devised for the latter can be seen as specific case instances of the former.

Cdlib aims to collect as much implementations as possible of existing  algorithms: suggestions on resources to be included are welcome. 

Nowadays, we are working to add support for dynamic community discovery and, among other stuff, we are planning to extend the library to multiplex community discovery.

If you like to contribute to the project feel free to contact me here or via email.

Best,
Giulio

**Comment by DonaldTsang** [comment]
I would hope that CDLib can include Role Detection algorithms as a bonus to Community Detection, as I am going to do research on the subject matter soon. I would hope that CDLib can grow and prosper with more features, algorithms, and optimizations.

**Comment by Yquetzal** [comment]
We hope so too, but the work on CDlib relies also on contributions by the community(or time is limited...), so, we can add the role detection module easily (actually, roles and communities are both particular cases of node clustering, so we can already represent roles as communities), but if you find implementations of methods or if you have made implementation yourself, it would help us a lot! Adding implementations to cdlib is simple, but if there is no implementation available, it is much more difficult.

**Comment by BrandonKMLee** [comment]
So it seems the two heads of this idea are @ryanrossi and @nkahmed, would you consider contacting them?
