### ISSUE TITLE
Rename your example tutorial notebook

### ISSUE THREAD

**Issue by akbaritabar** [GiulioRossetti/cdlib#140]
**Describe the bug**
I was checking out the `CDlib.ipynb` tutorial notebook on colab (https://colab.research.google.com/github/KDDComplexNetworkAnalysis/CNA_Tutorials/blob/master/CDlib.ipynb). At one point, I was happy with the things I learned so I decided to download it as a python script to use on my machine. Since the python file exported by Colab is named `CDlib.py` too, it was giving circular import error. 

**To Reproduce**
Export colab notebook to python script (not jupyter notebook, a simple python script). If you then are running python in the same directory, it won't import CDlib since the name is similar to the python script in the same directory.

**To Solve**
If you rename the jupyter notebook from "CDlib.ipynb" to something like "CDlib_tutorial.ipynb" will resolve this minor issue.

Thanks for CDlib!

**Comment by GiulioRossetti** [comment]
Thanks for the suggestion: you are completely right, it was a "naive" choice  for the notebook name. I'll change it ASAP!

**Comment by GiulioRossetti** [comment]
Tutorial notebook renamed.
