### ISSUE TITLE
[Clarification question] Is bipartite version of Infomap already implemented?

### ISSUE THREAD

**Issue by akbaritabar** [GiulioRossetti/cdlib#141]
I was checking out the implemented bipartite algorithms in documentation (https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/node_clustering.html?highlight=bipartite#bipartite-graph-communities) and also description of Infomap (https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/algs/cdlib.algorithms.infomap.html#cdlib.algorithms.infomap) and couldn't figure out if the bipartite version of Infomap (https://github.com/chrisbloecker/infomap-bipartite/tree/bipartite-only here is an example notebook showcasing its usage: https://github.com/chrisbloecker/infomap-bipartite/blob/master/examples/python/infomap-examples.ipynb) is already implemented, because it is not listed under bipartite algorithms.

Thanks (sorry if this is a naive question and I have missed it out somewhere, searching in documentation didn't yield results on this and infomap under algorithms seems to return only "NodeClustering" object and not a "BiNodeClustering" one)

**Comment by GiulioRossetti** [comment]
At the moment it is not implemented.
I'll add it as soon as possible.

**Comment by GiulioRossetti** [comment]
Infomap Bipartite implemented in master branch. Here's the [documentation](https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/algs/cdlib.algorithms.infomap_bipartite.html#cdlib.algorithms.infomap_bipartite).

**Comment by akbaritabar** [comment]
That is amazing news dear Giulio. Thanks.
I will check it as soon as I can find time and come back to report the result and close the issue.
