### ISSUE TITLE
tiles AttributeError

### ISSUE THREAD

**Issue by gebaltso** [GiulioRossetti/cdlib#143]
Hello and congratulations on your excellent work!

I have a problem using tiles algorithm. Actually I try your example
`from cdlib import algorithms
import dynetx as dn
import networkx as nx

dg = dn.DynGraph()
for x in range(10):
    g = nx.erdos_renyi_graph(200, 0.05)
    dg.add_interactions_from(list(g.edges()), t=x)
coms = algorithms.tiles(dg, 2)`

and get:
    coms = algorithms.tiles(dg, 2)
AttributeError: module 'cdlib.algorithms' has no attribute 'tiles'

Why is that so?
Thanks in advance.

**Comment by GiulioRossetti** [comment]
Hi,
I assume you have the library installed through pip: currently tiles is among the algorithms supported only in the github master branch version. It will be included in officially in the next package release.

If you would like to use it just uninstall cdlib and reinstall it from the repository.

**Comment by Yquetzal** [comment]
Just in case, install from the repository means using `pip install git+https://github.com/GiulioRossetti/cdlib.git`

**Comment by gebaltso** [comment]
Oh there is a note about this. Thank you very much.
One other question. After getting the result of coms object, is there a way to get the discovered communities at each timestamp? I mean something of the following form:
1 [2,4,7] [1,3] [8,9]
2 [2,3,4,7] [1,8,9]
.
.
where 1, 2 the timestamps and the following lists (containing the node ids) are the discovered communities at each timestamp.

**Comment by GiulioRossetti** [comment]
You can obtain something like that by combining the methods `get_observation_ids()` and `get_clustering_at(time)` of the TemporalClustering object (see the docs [here](https://cdlib.readthedocs.io/en/latest/reference/classes/temporal_clustering.html#cdlib.TemporalClustering.get_clustering_at).

The temporal clustering support is currently under development, any suggestion is welcome!
