### ISSUE TITLE
Visualization of Edge clustering

### ISSUE THREAD

**Issue by slq0** [GiulioRossetti/cdlib#145]
Hi, 

Can `cdlib.classes.edge_clustering.EdgeClustering` objects be plotted yet?
I could not find the answer in the user documentation. 

Plotting a graph from a `cdlib.classes.node_clustering.NodeClustering` object is easy:

```python
graph = nx.karate_club_graph()
communities = algorithms.louvain(graph)
pos = nx.spring_layout(graph)
viz.plot_network_clusters(graph, communities, pos)
```

But the same does not seem to work with an `..EdgeClustering` object:

```python
communities = algorithms.hierarchical_link_community(graph)
pos = nx.spring_layout(graph)
viz.plot_network_clusters(graph, communities, pos)
```

Thanks a lot for any help you can provide.
s.

**Comment by GiulioRossetti** [comment]
Hi,

unfortunately, you are right: at the moment EdgeClustering objects are not natively supported by visualization methods.

I'll work on it: in the meantime, my suggestion is to move from EdgeClustering to NodeClustering by reshaping the communities. It is not an ideal solution but it should work just fine.

Giulio

**Comment by slq0** [comment]
@GiulioRossetti : Thanks a lot for your quick reply. Will do.
