### ISSUE TITLE
plot_network_clusters() got an unexpected keyword argument 'top_k'

### ISSUE THREAD

**Issue by Sblbl** [GiulioRossetti/cdlib#146]
**Describe the bug**
top_k attr not recognised

**To Reproduce**
- CDlib version 2021-02-23
- Operating System big sur
- Python version conda 4.9.2 python 3.8

- Version(s) of CDlib required libraries

**Expected behavior**
Should plot the k most influential clusters, according to the docs

**Screenshots**
TypeError                                 Traceback (most recent call last)
<ipython-input-37-ec38eadbc32b> in <module>
      2 
      3 pos = nx.spring_layout(g)
----> 4 viz.plot_network_clusters(g, leiden_coms, pos, figsize=(20, 20), plot_labels=True, top_k=5)

TypeError: plot_network_clusters() got an unexpected keyword argument 'top_k'

**Comment by GiulioRossetti** [comment]
Hi,
I tested your snippet on the current version of the library (the one from the master branch of this repository) and it works. It is likely you have installed an older version of CDlib in your conda environment. 

Giulio

**Comment by Sblbl** [comment]
I'll verify, thank you very much!
