### ISSUE TITLE
Notes regarding niche centrality measures

### ISSUE THREAD

**Issue by BrandonKMLee** [GiulioRossetti/cdlib#148]
**Is your feature request related to a problem? Please describe.**

Similarly (not quite https://github.com/GiulioRossetti/cdlib/issues/114), there are centrality measures that can be poked at.
- [Consistency and differences between centrality measures across distinct classes of networks](https://journals.plos.org/plosone/article/figure?id=10.1371/journal.pone.0220061.t001)
- [Similarity Index based Link Prediction Algorithms in Social Networks: A Survey](https://www.semanticscholar.org/paper/Similarity-Index-based-Link-Prediction-Algorithms-A-Srilatha-Manjula/8e72fa77f3d788f3c67da1e1c6347c3aaf280723/figure/1)
- [Study on centrality measures in social networks: a survey](https://www.semanticscholar.org/paper/Study-on-centrality-measures-in-social-networks%3A-a-Das-Samanta/d938c15182ed2b83c8364ab1cce59601ee9244c1/figure/3)
- [Image of https://doi.org/10.1017/9781316105450.010](https://static.cambridge.org/binary/version/id/urn:cambridge.org:id:binary:20171027092037172-0306:9781316105450:08931tbl10_4.png?pub-status=live)
- [Social network analysis. Review of general concepts and use in preventive veterinary medicine](https://www.semanticscholar.org/paper/Social-network-analysis.-Review-of-general-concepts-Mart%C3%ADnez-L%C3%B3pez-P%C3%A9rez/ffb1d446af0fc2857e9eb8176713ba54c3d634e8/figure/4)

**Comment by BrandonKMLee** [comment]
One more odd piece of finding https://rdrr.io/cran/centiserve/ (seems like the original website got infected with a virus).
To compensate for my lack of observations in R libraries:
- https://www.rdocumentation.org/packages/tidygraph/versions/1.2.0/topics/centrality
- http://cran.nexr.com/web/packages/CINNA/vignettes/CINNA.html#various-types-of-centralities-computation

**Comment by BrandonKMLee** [comment]
Observing https://networkit.github.io/dev-docs/python_api/centrality.html

**Comment by BrandonKMLee** [comment]
https://github.com/GiulioRossetti/cdlib/issues/160 https://github.com/GiulioRossetti/cdlib/issues/161

**Comment by GiulioRossetti** [comment]
Hi,
although interesting, centrality measures are loosely related to the analytical task approached by CDlib.

Since they are not directly tied to clustering evaluation I don't think they should be integrated within the library.

**Comment by GiulioRossetti** [comment]
Interesting but not inherent to the package goals.

**Comment by BrandonKMLee** [comment]
Some more references to other centerality algorithms like `k-core` `subgraph centrality` `gateway coefficient` and `flow coefficient`
https://github.com/aestrivex/bctpy/blob/master/bct/algorithms/centrality.py
