### ISSUE TITLE
Newly Discovered ideas regarding Brokers & Structural Holes

### ISSUE THREAD

**Issue by BrandonKMLee** [GiulioRossetti/cdlib#149]
The concept of brokerage is important in understanding Roles and Community sub-structures.
[Dynamic change of manufacturing and service industries network in mobile ecosystems: The case of Korea](https://www.researchgate.net/figure/10-Types-of-ecological-roles-in-terms-of-productivity-and-brokerage-A-in-the-middle_fig5_273479980)
The five types of Brokers have different utilities (from most concentrated to least concentrated):
1. Coordinator (Message passing between people within Group A)
2. Gatekeeper (Person from Group A talks to the guard of B in order to get information to insider B)
3. Representative (Insider A uses in-group messenger to talk to people in Group B)
4. Consultant (Group A asks Group B for information, and Group B answers)
5. Liason (Group A talks to Group C through Group B)

This also references Donors (low input, high output) and Absorbers (diverse input, consolidated output)

Another idea to note is "structural holes", which is a generalization of Brokers, with Triangular relationships
[Extended structures of mediation: Re-examining brokerage in dynamic networks](https://www.sciencedirect.com/science/article/abs/pii/S0378873313000087)
[Brokerage as a Process: Decoupling Third Party Action from Social Network Structure](https://www.researchgate.net/figure/Three-Forms-of-Brokerage-Process_fig1_289329719)
- Conduit / Transfer (traditional brokerages, see above)
- Tertius Gaudens / Coordination (Centralized Power)
  - A => A & A (In-group delegation of power)
  - A => A & B (recruitment)
  - A => B & B  (Independent Mediation)
  - A => B & C (independent hierarchy)
  - (the arrows can be inverted for response effect)
- Tertius Iungens / Matchmaking (Third Party Ties)
  - A => (A <=> A) (In-group hiveminds)
  - A => (A <=> B) (befriending)
  - A => (B <=> C) (independent synergy)
  - (there can be complex forms through inversion or partiality of arrows)
- Cyclic (not mentioned in the paper, as it is somewhat problematic)

For Statistics [How Do Brokers Broker? Tertius Gaudens, Tertius Iungens, and the Temporality of Structural Holes](https://www.semanticscholar.org/paper/How-Do-Brokers-Broker-Tertius-Gaudens,-Tertius-and-Quintane-Carnabuci/dae3c4998403b74709134d16e3f54cbcaceaa5bd/figure/0)

**Comment by GiulioRossetti** [comment]
Brokerage implementation: https://github.com/reyagroup/networkx_additional_algorithms

**Comment by GiulioRossetti** [comment]
Interesting but not inherent to the package goals.
