### ISSUE TITLE
python-igraph pip installable, also on Windows

### ISSUE THREAD

**Issue by vtraag** [GiulioRossetti/cdlib#150]
You might be interested to know that `python-igraph` is `pip` installable since version 0.8. Similarly, `leidenalg` can also be installed using `pip` since version 0.8. This includes all major platforms (including Windows) for recent Python versions. You might be able to move some of the optional requirements to the normal requirements.

Additionally, you may be interested to know that we added conversion methods between `igraph` and `networkx` and `graph-tool`. These are available from version 0.8.3 onwards. This should enable you to remove (or simplify) some of the conversions you are making in `utils.py`.

**Comment by GiulioRossetti** [comment]
@vtraag Thanks for letting me know about this!
I'll update the code as soon as possible.

**Comment by GiulioRossetti** [comment]
@vtraag I am searching for the documentation on the conversion methods but without luck so far (my fault). 
Would you be so kind to provide me a link to it, please?

**Comment by vtraag** [comment]
The documentation is a bit rudimentary, I must confess. It is available at https://igraph.org/python/doc/api/igraph.Graph.html#from_networkx.

**Comment by Yquetzal** [comment]
If we go for the change, we need to be careful that it does not break with int nodes in networkx, I remember a tricky point I corrected in a previous bugfix (if nodes are already int in networkx, they need to be converted to string in i-graph and re-converted to int to match the original graph when returning the result, or something like that.)

**Comment by vtraag** [comment]
Good to know about that @Yquetzal! I think in the `python-igraph`, the `from_networkx` and `to_networkx` functions should retain the original Python types that are used. `networkx` does not have any explicit node ordering, while `igraph` explicitly does and uses integer indices to refer to nodes (although names are also supported). Perhaps some of the problems stem from there.

In any case, if there is something going wrong with the `from_networkx` or `to_networkx` functionality, we would be happy to learn about it and correct it!

**Comment by Yquetzal** [comment]
OK, I checked it and yes the _nx_name attributes retain the original type, so it solves the problem. The only thing we need to change is to check if the _nx_name attribute is present instead of the name attribute.
