### ISSUE TITLE
Implementaion of "Modularity measure of networks with overlapping communities"

### ISSUE THREAD

**Issue by zhqu1148980644** [GiulioRossetti/cdlib#153]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add an implementation of the mentioned paper. In this paper, the author proposed a method for detecting overlapping communities based on a modified version of the modularity score.

**Describe alternatives you've considered**

**Additional context**

**Comment by GiulioRossetti** [comment]
Hi, the issue description is not informative: could you elaborate on the issue?

**Comment by GiulioRossetti** [comment]
Here's the full paper reference:

> Lázár, Anna, Dániel Abel, and Tamás Vicsek. "[Modularity measure of networks with overlapping communities](https://iopscience.iop.org/article/10.1209/0295-5075/90/18001/pdf)." EPL (Europhysics Letters) 90.1 (2010): 18001.

@zhqu1148980644  are you aware of existing python implementations of such an algorithm? 
If so we can easily include them in CDlib; if not it could take a while for having the method integrated.

**Comment by BrandonKMLee** [comment]
TBH there should be guides for writing Issues in relations to papers, where references are paramount to searching

**Comment by BrandonKMLee** [comment]
There is a repo with that citation but https://github.com/aonghus/nxtools/blob/master/nxtools/algorithms/community/quality.py

**Comment by GiulioRossetti** [comment]
> TBH there should be guides for writing Issues in relations to papers, where references are paramount to searching

You are right, my bad.
I updated the feature request template specifying a "reference" section.

I'll give a look at the suggested repo, thanks.

Giulio

**Comment by GiulioRossetti** [comment]
Integration in progress (#179).
