### ISSUE TITLE
Bug in calculation of surprise

### ISSUE THREAD

**Issue by abdkarr** [GiulioRossetti/cdlib#154]
**Describe the bug**
There is an error in the following line of calculation of asymptotic surprise:

`sp = m * (q * np.log(q / qa) + (1 - q) * np.log2((1 - q) / (1 - qa)))`

This is the line 769 of `fitness.py` file (version 0.2.0). The log2 in the second term should be log.

**Comment by GiulioRossetti** [comment]
Hi, the fix has been pushed to the master branch.
It will be included in the next package release.
