### ISSUE TITLE
Feature: PyCABeM evaluation framework inclusion

### ISSUE THREAD

**Issue by BrandonKMLee** [GiulioRossetti/cdlib#159]
**Is your feature request related to a problem? Please describe.**
Observing https://github.com/eXascaleInfolab/PyCABeM is written completely in Python it might be good to take a look

**Additional context**
Algorithms: HiReCS, Oslom2, GANXiS

**Comment by GiulioRossetti** [comment]
All algorithms written in Python from the linked resource are already integrated into CDlib; the others have C/Java implementations that make them unsuitable for (transparent) integration.
