### ISSUE TITLE
Leverage centrality

### ISSUE THREAD

**Issue by BrandonKMLee** [GiulioRossetti/cdlib#160]
Please use the following template to describe your feature request.
Feel free to remove those sections that do not apply to your specific request.

**Is your feature request related to a problem? Please describe.**
This is a centrality method that is slightly more independent from Degree Centrality from Betweenness Centrality.

**Reference.**
http://igraph.wikidot.com/r-recipes#toc10 and https://www.centiserver.org/centrality/Leverage_Centrality/

**Describe the solution you'd like**
Psuedo-Python:
```
for node i in graph:
    x = degree_centrality(graph)
    y = [graph.number_of_edges(j) for j in graph]
    return [average([((x[j]-x[k])/(x[j]+x[k])) for k in graph.neighbors(j)]) for j in graph]
```

**Comment by GiulioRossetti** [comment]
Interesting but not inherent to the package goals.
