### ISSUE TITLE
Laplacian Centrality

### ISSUE THREAD

**Issue by BrandonKMLee** [GiulioRossetti/cdlib#161]
Please use the following template to describe your feature request.
Feel free to remove those sections that do not apply to your specific request.

**Is your feature request related to a problem? Please describe.**
Laplacian Centrality is one of the centrality that is removes degree centrality relations from closeness centrality
Other centrality measures that are removed from degree centrality is Eigenvector Centrality and Information Centrality

**Reference.**
https://andrewpwheeler.com/2015/07/29/laplacian-centrality-in-networkx-python/

**Comment by GiulioRossetti** [comment]
Interesting but not inherent to the package goals.
