### ISSUE TITLE
Directed Louvain Algorithm

### ISSUE THREAD

**Issue by BrandonKMLee** [GiulioRossetti/cdlib#162]
Please use the following template to describe your feature request.
Feel free to remove those sections that do not apply to your specific request.

**Is your feature request related to a problem? Please describe.**
Just discovered that directed Louvain algorithm exists, yet it is not included in CDLib.

**Reference.**
- https://hal.archives-ouvertes.fr/hal-01231784/document
- https://github.com/nicolasdugue/DirectedLouvain
- https://github.com/graphology/graphology-communities-louvain#references

**Additional Context**
Directed Modularity also exists! https://igraph.org/c/doc/igraph-Community.html#igraph_modularity

**Comment by BrandonKMLee** [comment]
Other Surveys that might outline possible directed graph community detection: https://arxiv.org/pdf/1308.0971.pdf 

Spectral Algorithms for Community Detection in Directed Networks https://jmlr.org/papers/volume21/18-581/18-581.pdf
Communities in directed graphs: Finding directed community structures using triads https://hal.archives-ouvertes.fr/hal-01849601v2/document

**Comment by GiulioRossetti** [comment]
Please refactor the request in #178.
