### ISSUE TITLE
OSLOM (Directed Graph CD Algorithm)

### ISSUE THREAD

**Issue by BrandonKMLee** [GiulioRossetti/cdlib#163]
Please use the following template to describe your feature request.
Feel free to remove those sections that do not apply to your specific request.

**Is your feature request related to a problem? Please describe.**
Discovering Community Detection Algorithms that are DiGraph compatible.

**Reference.**
- used in https://ccc.inaoep.mx/~ariel/A%20consensus%20graph%20clustering%20algorithm%20for%20directed%20networks.pdf
- http://www.oslom.org/
- https://arxiv.org/abs/1012.2363
- Python library from Cytoscape https://github.com/idekerlab/cdoslom
- https://pypi.org/project/oslom-runner/

**Comment by GiulioRossetti** [comment]
Unfortunately, the integration of OSLOM is not trivial.
The suggested package is just a python "runner" for the classic C implementation - that needs to be compiled and installed separately. In absence of a complete python implementation, we have to put this request on hold.

**Comment by GiulioRossetti** [comment]
Please refactor the request in #178.
