### ISSUE TITLE
Documentation: Synonym issues, e.g. Split-Join Distance vs Van Dongen Measure

### ISSUE THREAD

**Issue by BrandonKMLee** [GiulioRossetti/cdlib#164]
In Most papers e.g. https://i11www.iti.kit.edu/extra/publications/dggw-ecgc-08.pdf they use the term "Van Dongen Measure" to refer to Split-Join Distance in https://igraph.org/r/doc/split_join_distance.html 

The same can be said about "Louvain" vs "multilevel" and others. It might be good to address the possible wording discrepancies between academic papaers.

**Comment by GiulioRossetti** [comment]
Network science is a particularly interdisciplinary field: if we start disambiguating entity naming we'll easily go down the rabbit hole!
I agree with the point you made, but it is quite complex to apply this approach in an extensive manner.

**Comment by BrandonKMLee** [comment]
That I hope that there is a Wiki-like way of addressing the information and allow people to collaborate the editing and tracking of terms.

**Comment by GiulioRossetti** [comment]
> That I hope that there is a Wiki-like way of addressing the information and allow people to collaborate the editing and tracking of terms.

The documentation files are available within the repository: any suggestion/editing received as a pull request is evaluated and, if deemed useful, integrated. No need to set up an additional wiki.
