### ISSUE TITLE
AttributeError: module 'cdlib.algorithms' has no attribute 'XXX'

### ISSUE THREAD

**Issue by BrandonKMLee** [GiulioRossetti/cdlib#166]
**Describe the bug**
```
from cdlib import algorithms
<insert code for creating a Graph here, with G being the variable>
for i in [algorithms.gemsec, algorithms.head_tail, algorithms.kcut, algorithms.lswl, algorithms.lswl_plus, algorithms.paris, algorithms.pycombo, algorithms.ricci_community, algorithms.scd, algorithms.threshold_clustering]:
  communities = i(G)
```
**To Reproduce**
- CDlib version 0.2.0
- Operating System Windows 10
- Python version 3.8

**Expected behavior**
expect that this would work since other algorithms checks out.
`[algorithms.aslpaw, algorithms.chinesewhispers, algorithms.edmot, algorithms.der, algorithms.cpm, algorithms.ga, algorithms.gdmp2, algorithms.greedy_modularity, algorithms.infomap,   algorithms.significance_communities, algorithms.surprise_communities, algorithms.walktrap, algorithms.sbm_dl, algorithms.sbm_dl_nested]`

 **Utility**
To quickly iterate through multiple algorithms at once

**Comment by GiulioRossetti** [comment]
Moreover, there is already a way to pool algorithms. See https://cdlib.readthedocs.io/en/latest/reference/ensemble.html#multiple-instantiation

**Comment by BrandonKMLee** [comment]
@GiulioRossetti what if instead of pooling, we are trying to do cross-model evaluations?

**Comment by GiulioRossetti** [comment]
> @GiulioRossetti what if instead of pooling, we are trying to do cross-model evaluations?

To perform cross-model evaluation/comparison, given a graph you still need to compute a set of clusterings, each applying a different algorithm to it. For such a purpose pooling (or even grid search if you aim to fine-tune model parameters) is fine since it only offers a standard way to structure multi-model experiments.
