### ISSUE TITLE
Documentation: Clear Addressing of which CD Algorithms can or cannot use Directed Graphs.

### ISSUE THREAD

**Issue by BrandonKMLee** [GiulioRossetti/cdlib#167]
List of algorithms that can't handle Directed Graphs:
- label_propagation
- louvain
- markov_clustering
- spinglass
- aslpaw (slow)
- edmot
- der
- greedy_modularity
- infomap
- sbm_dl
- sbm_dl_nested

List of algorithms that CAN handle Directed Graphs:
- eigenvector
- leiden
- rb_pots
- rber_pots
- cpm
- significance_communities
- surprise_communities
- walktrap
- belief  (slow)
- ga  (slow)

List of algorithms that have not been tested due to odd bugs (Frozen Graph):
- markov_clustering
- chinesewhispers
- gdmp2

List of algorithms that have not been tested due to requiring extra params:
- https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/algs/cdlib.algorithms.agdl.html#cdlib.algorithms.agdl
- https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/algs/cdlib.algorithms.async_fluid.html#cdlib.algorithms.async_fluid
- https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/algs/cdlib.algorithms.em.html#cdlib.algorithms.em
- https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/algs/cdlib.algorithms.girvan_newman.html#cdlib.algorithms.girvan_newman
- https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/algs/cdlib.algorithms.lswl.html#cdlib.algorithms.lswl
- https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/algs/cdlib.algorithms.mod_m.html#cdlib.algorithms.mod_m
- https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/algs/cdlib.algorithms.mod_r.html#cdlib.algorithms.mod_r
- https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/algs/cdlib.algorithms.scan.html#cdlib.algorithms.scan

**Comment by BrandonKMLee** [comment]
Others that are not tested due to AttributeError: https://github.com/GiulioRossetti/cdlib/issues/166

**Comment by BrandonKMLee** [comment]
For those that explicitly cannot handle DiGraphs, it might be a good idea to convert DiGraph into a regular Graph at runtime and throw a warning
see: https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/algs/cdlib.algorithms.eigenvector.html
see also: https://github.com/igraph/igraph/blob/cf684b5ce44ac41732a7f61884b390e24172047a/src/community/leading_eigenvector.c#L530

**Comment by BrandonKMLee** [comment]
Possible solution: Does conversion with https://networkx.org/documentation/stable/reference/classes/generated/networkx.DiGraph.to_undirected.html (could possibly be automated)

**Comment by GiulioRossetti** [comment]
> Possible solution: Does conversion with https://networkx.org/documentation/stable/reference/classes/generated/networkx.DiGraph.to_undirected.html (could possibly be automated)
> In context of social media: whether it is a two-way follow vs one-way.

This issue needs only to be addressed in the documentation and by raising detailed errors in case of unsupported graph types.
Implicit type conversion is not the solution: the user needs to be aware of CD algorithms requirements.

**Comment by BrandonKMLee** [comment]
It would be useful to have this documented, would PR for this.

**Comment by GiulioRossetti** [comment]
I completely agree. 

I would suggest, however, to perform such an annotation in a structured way including information on more aspects - i.e., support for directed/undirected, weighted/unweighted, node attributes...

The optimal way to do it would be looking at the original papers for each method in CDlib, test the implementation and annotate accordingly (maybe pointing out discrepancies in case of partial support).  

Then we can enrich the individual method's description pages and also provide a dedicated page in the docs.

**Comment by GiulioRossetti** [comment]
All methods' descriptions have been updated with annotations reporting the supported graph types.
A descriptive [table](https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/algorithms.html) collecting algorithms' properties has been added to the documentation.
