### ISSUE TITLE
Installation of Graph-Tool through Conda

### ISSUE THREAD

**Issue by BrandonKMLee** [GiulioRossetti/cdlib#170]
Currently CDLib recommended using Brew or Apt-likes to install Graph-Tool since the original PyPi repository is outdated (2.37 vs 2.11), but the official website recommended an alternative: `conda create --name gt -c conda-forge graph-tool
conda activate gt`

https://github.com/GiulioRossetti/cdlib/blob/67efbff29edde594bf577551335637850f555d58/cdlib/algorithms/crisp_partition.py#L997

**Comment by GiulioRossetti** [comment]
Nothing to change: the link in the warning points to all possible installation methodologies for graph-tool, including conda.
