### ISSUE TITLE
avg_transitivity fails

### ISSUE THREAD

**Issue by seoanezonjic** [GiulioRossetti/cdlib#172]
**Describe the bug**
When I cluster a network using methods such as wcommunity or aslpaw the evaluation method avg_transitivity (maybe other methods are affected) fails with the following message:
python3.7/site-packages/networkx/algorithms/cluster.py", line 267, in average_clustering
    return sum(c) / len(c)
ZeroDivisionError: division by zero 

I suspect that the problem is that the communities have overlapping nodes. When I use other methods, such as rber_pots, the error dissapears.

**To Reproduce**
- The network: [MERGED_assoc_sample.txt](https://github.com/GiulioRossetti/cdlib/files/6539629/MERGED_assoc_sample.txt)
- Perform clustering with wcommunity or aslpaw methods (rber_pots don't give error)
- Use avg_transitivity with the obtained community object.
- CDlib version: 0.2.0
- Operating System: Suse
- Python version: 3.7

**Expected behavior**
Obtain the avg_transitivity  result or get some null value if the method don't fit with the clustering data.

**Comment by GiulioRossetti** [comment]
Hi,

I tried to replicate the issue on your data with the following code:


```
import networkx as nx
import cdlib.algorithms as alg
import cdlib.evaluation as eval

g = nx.Graph()
with open("MERGED_assoc_sample.txt") as f:
    for l in f:
        l = l.rstrip().split("\t")
        g.add_edge(l[0], l[1], weight=float(l[2]))

coms = alg.aslpaw(g)
res = eval.avg_transitivity(g, coms)
print(res)
```

however, it seems to correctly produce the desired output without raising any error (the same applies substituting aslapaw with wCommunity, demon and other overlapping algorithms).

Can you please try updating to the latest version of the library and test again?

Giulio

**Comment by seoanezonjic** [comment]
Hi @GiulioRossetti 
I've executed the example with cdlib 0.2.0 (in pip) and cdlib 0.2.1 (this repo). With the latter, the error dissapears but when I execute with aslpaw algorithm I obtain the following error:
`Traceback (most recent call last):
  File "/mnt/home/soft/soft_bio_267/programs/x86_64/scripts/cdlib_clusterize.py", line 153, in <module>
    communities = algorithms.aslpaw(g)
  File "/mnt/home/soft/soft_bio_267/programs/x86_64/python/workgroup-env/lib/python3.7/site-packages/cdlib/algorithms/overlapping_partition.py", line 1026, in aslpaw
    coms = ASLPAw(g).adj
  File "/mnt/home/soft/soft_bio_267/programs/x86_64/python/workgroup-env/lib/python3.7/site-packages/ASLPAw_package/ASLPAw_module.py", line 92, in ASLPAw
    return __ASLPAw_networkx(data_graph, Repeat_T, seed)
  File "/mnt/home/soft/soft_bio_267/programs/x86_64/python/workgroup-env/lib/python3.7/site-packages/ASLPAw_package/ASLPAw_module.py", line 54, in __ASLPAw_networkx
    digraph_of_node_labels_and_frequencies = __remove_low_frequency_label(community_label_queues_for_nodes)
  File "/mnt/home/soft/soft_bio_267/programs/x86_64/python/workgroup-env/lib/python3.7/site-packages/ASLPAw_package/ASLPAw_module.py", line 24, in __remove_low_frequency_label
    clf = IsolationForest(n_estimators = 120, contamination = 'auto', behaviour = 'new')
  File "/mnt/home/soft/soft_bio_267/programs/x86_64/python/workgroup-env/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'behaviour'`

What changed between 0.2.0 and 0.2.1 cdlib versions?

Thank you
Pedro Seoane

**Comment by GiulioRossetti** [comment]
In the upcoming release ASLPAw will become an optional dependency. This because the last version of such package relies on a few C libraries that are not straightforward to install in an automated way (see the updated version of CDlib installation instructions). 

This choice has been made to remove a pinned dependency to an old sklearn version,  required by the previous ASLPAw implementation.

I'm really sorry for the issue: to address it I suggest to perform a clean install of CDlib in a python>=3.8 environment.
