### ISSUE TITLE
Role-based Label Propagation Algorithm for Community Detection

### ISSUE THREAD

**Issue by BrandonKMLee** [GiulioRossetti/cdlib#176]
There are more versions of Label Propagation algorithms out there that exist.

**Reference.**

- https://arxiv.org/ftp/arxiv/papers/1601/1601.06307.pdf
- LPAD [5] I.X. Leung, P. Hui, P. Lio, and J. Crowcroft, Towards real-time community detection in
large networks, Phys. Rev. E 79.6 (2009) 066107
- DPA [11] L. Šubelj, and M. Bajec, Unfolding communities in large complex networks: Combining
defensive and offensive label propagation for core extraction, Phys. Rev. E 83.3 (2011)
036103

**Comment by GiulioRossetti** [comment]
Please refactor the request in #178.
