### ISSUE TITLE
Community Detection in Social Networks Using Affinity Propagation with Adaptive Similarity Matrix

### ISSUE THREAD

**Issue by BrandonKMLee** [GiulioRossetti/cdlib#177]
**Is your feature request related to a problem? Please describe.**
Affinity Propagation is a more effective alternative to Label Propagation in a sparse graph

**Reference.**
- https://www.liebertpub.com/doi/pdf/10.1089/big.2019.0143

**Comment by GiulioRossetti** [comment]
Please refactor the request in #178.
