### ISSUE TITLE
[Requirements] Dependency breaking change in evaluation package

### ISSUE THREAD

**Issue by victor-mariano-leite** [GiulioRossetti/cdlib#181]
**Describe the bug**
After pip installing the package, when importing omega_index_py3 dependency path breaks the import.

It seems that yesterday omega-index-py3 package has been updated and the import style changed also as Snyk Advisor reports [here](https://snyk.io/advisor/python/omega-index-py3).

The current functional version is 0.3 not 0.3.2 (weirdly a minor change, maybe the maintainer will fix this), but i didn't find the repository on GitHub to start an issue to let'em know this is happening.

**To Reproduce**

Prerequisites:
- CDlib latest release
- Operating System: Windows 10 Pro -> WSL 2 / Ubuntu 20.04
- Python version: 3.8.10

Steps:
1. `pip install cdlib`
2. Try to import it

**Expected behavior**
Import the package correctly

**Comment by GiulioRossetti** [comment]
Hi, 
In the last release of CDlib such dependency has been removed. I'll check for possible connected issue, in the meantime try with a fresh cdlib install on a clean environment.

**Comment by victor-mariano-leite** [comment]
Thanks for the heads up, it solved my problem :)
