### ISSUE TITLE
infomap dependency error when importing algorithms

### ISSUE THREAD

**Issue by lizgzil** [GiulioRossetti/cdlib#182]
**Describe the bug**

I'm having problems import algorithms, it seems to be because of a problem with the `infomap` dependency.

(personal info X'd out)
```
>>> from cdlib import algorithms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "XXX/miniconda3/envs/XXX/lib/python3.8/site-packages/cdlib/algorithms/__init__.py", line 2, in <module>
    from .crisp_partition import *
  File "XXX/miniconda3/envs/XXX/lib/python3.8/site-packages/cdlib/algorithms/crisp_partition.py", line 2, in <module>
    import infomap as imp
  File "XXX/miniconda3/envs/XXX/lib/python3.8/site-packages/infomap.py", line 34, in <module>
    import _infomap
ImportError: dlopen(XXX/miniconda3/envs/XXX/lib/python3.8/site-packages/_infomap.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: XXX/miniconda3/envs/XXX/lib/python3.8/site-packages/_infomap.cpython-38-darwin.so
  Reason: image not found
```

**To Reproduce**
- CDlib version: 0.2.3
- Operating System: macOS-10.16-x86_64-i386-64bit
- Python version: 3.8.10

**Expected behavior**
Algorithms to be able to be imported without error.

**Additional context**
`from cdlib import ensemble` works correctly.

I get issue #181 for cdlib==0.2.0 and cdlib==0.2.1

**Comment by GiulioRossetti** [comment]
It seems related to a broken installation o f the Infomap dependency. Have you installed cdlib using pip or anaconda?
Is this issue common to both installation methodologies (starting from clean python envs)?

Tbh I haven't tried so far to install Infomap on osx so I don't know if this is a known issue.

**Comment by lizgzil** [comment]
I'm installing it with pip.

I get the issue described in this issue #181 for `cdlib==0.2.0 ` and `cdlib==0.2.1`, and it's just for the latest `cdlib==0.2.3` that I get the error with infomap. (I don't think I'd used a clean env when I did the 0.2.0 test earlier - will change the issue description).

I'll have a dig around with infomap and see if I can find anything.

**Comment by GiulioRossetti** [comment]
Use  v0.2.3, and try with conda.
Infomap has some C dependencies that needs to be compiled when installed with pip: maybe the conda package solves the issue.

**Comment by lizgzil** [comment]
hurray 🎉 that made it work. Thank you for your help @GiulioRossetti !

Just for clarity I installed it with:
```
conda config --add channels giuliorossetti
conda config --add channels conda-forge
conda install cdlib
```
