### ISSUE TITLE
Wcommunity algorithm problem

### ISSUE THREAD

**Issue by sk4na** [GiulioRossetti/cdlib#186]
Hey there,

I was using the wcommunity algorithm on the attached dataset, and realized that the output given contained a few repeated clusters. They have different cluster id, but  they actually are the exact same communities formed by the same nodes. Furthermore, from the 3215 clusters identified by the algorithm, 2815 were formed by just two or one node.

This dataset was also tested using other methods such as the linkcomm algorithm (https://cran.r-project.org/web/packages/linkcomm/index.html), and no repeated clusters or communities formed by less than 3 nodes were found.

[OMIM_cleaned_reliable_pairs.txt](https://github.com/GiulioRossetti/cdlib/files/6829490/OMIM_cleaned_reliable_pairs.txt)

**Comment by GiulioRossetti** [comment]
Hi,
I'll check the community duplication issue. For what concerns the presence of single/two node communities: that's totally acceptable, not all clustering algorithms impose a minimum size for individual nodes' groups.

**Comment by GiulioRossetti** [comment]
Duplication issue addressed.
