### ISSUE TITLE
avg_distance raise an exception when used with unconnected clusters

### ISSUE THREAD

**Issue by seoanezonjic** [GiulioRossetti/cdlib#188]
**Describe the bug**
When avg_distance evaluation metric is used to evaluate an unconnected cluster, cdlib breaks with the following error:

raise nx.NetworkXError("Graph is not connected.")

**To Reproduce**
- CDlib version: Any
- Operating System: Any
- Python version: Any
- Version(s) of CDlib required libraries: Any

**Expected behavior**
Instead a networkx failure, that avg_distance returns a None or Inf value that tag the cluster as unconnected.

Thank you in advance
Pedro Seoane

**Comment by GiulioRossetti** [comment]
"Fail early, fail loudly"
This is exactly the case in which raising an error is more informative than proposing an arbitrary value (also for type consistency).

I don't see it as a bug but as the expected behavior.

**Comment by seoanezonjic** [comment]
Hi @GiulioRossetti,
 
I'm afraid that I do not agree with you. The avg_distance is a cluster evaluation method, such as conductance, avg_transitivity, surprise, etc. Some of them, when they cannot be computed (for example, a div by zero error), give a None value when the FitnessResult object is accessed or the cluster list is obtained. I expected that the avg_distance method behaved in the same way than the other metrics. In fact, I use a vector of evaluation metrics and I iterate it to get all the metric values. This metric is the only one that breaks my code. The problem is that I cannot try/catch this metric because when one cluster is unconnected, I loss the rest of cluster results. 

Thank you in advance for your time and help.
Pedro Seoane.

**Comment by GiulioRossetti** [comment]
I see your point: you can find a quick fix in the latest commit I made on the repository.
Now all FitnessResult indicators are set to None whenever a similar issue emerges. 
Try it and let me know.

Giulio

**Comment by seoanezonjic** [comment]
Hi @GiulioRossetti,
 
I'm used the last version and works as  I've expected but there is a minor problem. I think that you have used a try/catch approximation to handle the specific problem that I described and then, the default value is given in FitnessResult object. In a few tests, I discovered that some clusters have ids that cannot be mapped to STRING network, so this situation also raise a networkX exception and I obtain the FitnessResult  to None. I think that the avg_distance has to give None if network path is not found and raise the networkX exception otherwise. In fact, networkX has the NetworkXNoPath exception (https://networkx.org/documentation/stable/reference/exceptions.html#networkx.NetworkXNoPath) to check this specific situation. What do you think about this?

Thank you in advance for your time and help.
Pedro Seoane.

**Comment by GiulioRossetti** [comment]
> I'm used the last version and works as I've expected but there is a minor problem. I think that you have used a try/catch approximation to handle the specific problem that I described and then, the default value is given in FitnessResult object. In a few tests, I discovered that some clusters have ids that cannot be mapped to STRING network, so this situation also raise a networkX exception and I obtain the FitnessResult to None. I think that the avg_distance has to give None if network path is not found and raise the networkX exception otherwise. In fact, networkX has the NetworkXNoPath exception (https://networkx.org/documentation/stable/reference/exceptions.html#networkx.NetworkXNoPath) to check this specific situation. What do you think about this?
> 

Could you please provide me a minimal example of a Network that generates this specific event (failed mapping to string network)?

If the mapping issue is related to cdlib network operations/transformations it could be better to address it directly rather than raising an exception.

**Comment by seoanezonjic** [comment]
Hi @GiulioRossetti 
Don't worry about CDLIB mapping issues, is a minor problem from my side. I build clusters outside of cdlib and I evaluate them with CDLIB and some gene ids of the clusters are not in this specific STRING network. I give you the files that generate this event:
network: [string.zip](https://github.com/GiulioRossetti/cdlib/files/6877821/string.zip)
clusters: [cluster_no_mappedIDs.txt](https://github.com/GiulioRossetti/cdlib/files/6877835/cluster_no_mappedIDs.txt)

Thank you in advance for your time and help.
Pedro Seoane.
