### ISSUE TITLE
error during cdlib installation

### ISSUE THREAD

**Issue by aj-cmsc90** [GiulioRossetti/cdlib#189]
**Describe the bug**
I am trying to install cdlib with pip and pip3 but some errors occur everytime. I have also upgraded pip and setuptools but nothing works. Please suggest any solution. 

error is:
  Running setup.py install for gensim ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python385\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ajaha\\AppData\\Local\\Temp\\pip-install-nrcs9ehc\\gensim_62451c53d9fc42f0a023936b3410aeb7\\setup.py'"'"'; __file__='"'"'C:\\Users\\ajaha\\AppData\\Local\\Temp\\pip-install-nrcs9ehc\\gensim_62451c53d9fc42f0a023936b3410aeb7\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ajaha\AppData\Local\Temp\pip-record-6948vtjl\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\python385\Include\gensim'
         cwd: C:\Users\ajaha\AppData\Local\Temp\pip-install-nrcs9ehc\gensim_62451c53d9fc42f0a023936b3410aeb7\
ERROR: Command errored out with exit status 1: 'c:\python\python385\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ajaha\\AppData\\Local\\Temp\\pip-install-nrcs9ehc\\gensim_62451c53d9fc42f0a023936b3410aeb7\\setup.py'"'"'; __file__='"'"'C:\\Users\\ajaha\\AppData\\Local\\Temp\\pip-install-nrcs9ehc\\gensim_62451c53d9fc42f0a023936b3410aeb7\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ajaha\AppData\Local\Temp\pip-record-6948vtjl\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\python385\Include\gensim' Check the logs for full command output.
**To Reproduce**
- CDlib version
- Operating System Windows 10
- Python version 3.8.5
- Version(s) of CDlib required libraries

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Yquetzal** [comment]
From the first line, it seems that the problem is when installing a dependence, `gensim`. Could you try to install it alone ?
https://pypi.org/project/gensim/

If it fails, the problem is not from cdlib but from this library. In that case the only thing we can do is move the methods that depend on it in the "optional" section, if this problem is common.

**Comment by GiulioRossetti** [comment]
Another option to address this issue (that should fix all main problems with windows installations) is to use the CDlib conda package, as reported in the documentation.

**Comment by sitiharyanti** [comment]
Building wheels for collected packages: python-Levenshtein
  Building wheel for python-Levenshtein (setup.py): started
  Building wheel for python-Levenshtein (setup.py): finished with status 'error'
  Running setup.py clean for python-Levenshtein
Failed to build python-Levenshtein
Installing collected packages: python-Levenshtein, pyclustering, pulp, pooch, nf1, markov-clustering, eva-lcd, dynetx, demon, chinese-whispers, bimlpa, angel-cd, cdlib
    Running setup.py install for python-Levenshtein: started
    Running setup.py install for python-Levenshtein: finished with status 'error'
  running egg_info
  writing python_Levenshtein.egg-info\PKG-INFO
  writing dependency_links to python_Levenshtein.egg-info\dependency_links.txt
  writing entry points to python_Levenshtein.egg-info\entry_points.txt
  writing namespace_packages to python_Levenshtein.egg-info\namespace_packages.txt
  writing requirements to python_Levenshtein.egg-info\requires.txt
  writing top-level names to python_Levenshtein.egg-info\top_level.txt
  reading manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*pyc' found anywhere in distribution
  warning: no previously-included files matching '*so' found anywhere in distribution
  warning: no previously-included files matching '.project' found anywhere in distribution
  warning: no previously-included files matching '.pydevproject' found anywhere in distribution
  adding license file 'COPYING'
  writing manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
  copying Levenshtein\_levenshtein.c -> build\lib.win-amd64-3.9\Levenshtein
  copying Levenshtein\_levenshtein.h -> build\lib.win-amd64-3.9\Levenshtein
  running build_ext
  building 'Levenshtein._levenshtein' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for python-Levenshtein
    ERROR: Command errored out with exit status 1:
     command: 'D:\Anaconda1\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-i21qufa5\\python-levenshtein_7966d60730b14b39bebf866d188f6ad1\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-i21qufa5\\python-levenshtein_7966d60730b14b39bebf866d188f6ad1\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-2aioxj30\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Anaconda1\Include\python-Levenshtein'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-i21qufa5\python-levenshtein_7966d60730b14b39bebf866d188f6ad1\
    Complete output (28 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\Levenshtein
    copying Levenshtein\StringMatcher.py -> build\lib.win-amd64-3.9\Levenshtein
    copying Levenshtein\__init__.py -> build\lib.win-amd64-3.9\Levenshtein
    running egg_info
    writing python_Levenshtein.egg-info\PKG-INFO
    writing dependency_links to python_Levenshtein.egg-info\dependency_links.txt
    writing entry points to python_Levenshtein.egg-info\entry_points.txt
    writing namespace_packages to python_Levenshtein.egg-info\namespace_packages.txt
    writing requirements to python_Levenshtein.egg-info\requires.txt
    writing top-level names to python_Levenshtein.egg-info\top_level.txt
    reading manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*pyc' found anywhere in distribution
    warning: no previously-included files matching '*so' found anywhere in distribution
    warning: no previously-included files matching '.project' found anywhere in distribution
    warning: no previously-included files matching '.pydevproject' found anywhere in distribution
    adding license file 'COPYING'
    writing manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
    copying Levenshtein\_levenshtein.c -> build\lib.win-amd64-3.9\Levenshtein
    copying Levenshtein\_levenshtein.h -> build\lib.win-amd64-3.9\Levenshtein
    running build_ext
    building 'Levenshtein._levenshtein' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\Anaconda1\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-i21qufa5\\python-levenshtein_7966d60730b14b39bebf866d188f6ad1\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-i21qufa5\\python-levenshtein_7966d60730b14b39bebf866d188f6ad1\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-2aioxj30\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Anaconda1\Include\python-Levenshtein' Check the logs for full command output.
​

**Comment by sitiharyanti** [comment]
Thank you GiulioRossetti. I just read your comment.
