### ISSUE TITLE
Misleading docs in cdlib.algorithms.label_propagation algorithm

### ISSUE THREAD

**Issue by Geeshang** [GiulioRossetti/cdlib#190]
https://github.com/GiulioRossetti/cdlib/blob/d60d4af5c2f825a378f2639fe135a36b6732bf67/cdlib/algorithms/crisp_partition.py#L1139

The method `cdlib.algorithms.label_propagation` is a wrapper of NetworkX  `label_propagation_communities`，which is based on a semi-synchronous variant introduced in "Cordasco, G., & Gargano, L. (2010, December). Community detection via semi-synchronous label propagation algorithms". The docs describe it as a 2007 asynchronous paper.

**Comment by GiulioRossetti** [comment]
@Geeshang thanks for highlighting such inconsistency: I'll update the reference ASAP.

Giulio
