### ISSUE TITLE
The cdlib library cannot import infomap

### ISSUE THREAD

**Issue by WanyongFeng** [GiulioRossetti/cdlib#192]
**Describe the bug**

**To Reproduce**
- CDlib version
- Operating System 
- Python version
- Version(s) of CDlib required libraries

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by GiulioRossetti** [comment]
It is a known issue due to the recent update of the infomap package. I am working to address the issue.

**Comment by WanyongFeng** [comment]
Thank you for your response, I will try to update the conda one I am using right now. I have another question, for surprise and leiden method, although the document says that they do not support weight, but there is a weight parameter, can I understand that if I use the weight parameter, then the method will support the undirected weighted graph? For the louvain method, can I understand that if I pass in an undirected weighted graph, the method will take care of it too?

**Comment by nick-trustlab** [comment]
Any updates?  There was some talk of a [workaround here](https://github.com/mapequation/infomap/issues/322) but I can't seem to link the executable that gets compiled to the python library.

**Comment by nick-trustlab** [comment]
What was the solution?

**Comment by GiulioRossetti** [comment]
I just released CDlib v0.3.0.
In case the infomap package is not installed the library will fall back to the python-igraph implementation.
