### ISSUE TITLE
Cannot import module viz

### ISSUE THREAD

**Issue by nahuelalmeira** [GiulioRossetti/cdlib#193]
**Describe the bug**
Error is raised when loading `community` package

**To Reproduce**
- CDlib version: 0.2.5
- Operating System: Google Colab
- Python version: 3.7.12

Minimal colab [example](https://colab.research.google.com/drive/16qB516OA7xvs6AW6n5al0APn-KO03liW?usp=sharing).

**Comment by GiulioRossetti** [comment]
The minimum python version required by CDlib is the 3.8.

**Comment by nahuelalmeira** [comment]
I have updated the Colab python version to 3.8 but the error continues. It appears to be a problem with the python-louvain package, so I wrote an issue in their github repository.

**Comment by Yquetzal** [comment]
> I have updated the Colab python version to 3.8 but the error continues. It appears to be a problem with the python-louvain package, so I wrote an issue in their github repository.

I observed the problem. A quick fix: you can do:
```!pip uninstall python-louvain```
```!pip install python-louvain```
I checked it solves the problem.
But I'll try to propose a better fix. Seems specific to google-colab.

**Comment by shirleykq-zhang** [comment]
Hi, I had the same issue running with google-colab. Reinstalling python-louvain didn't solve the problem.

**Comment by Yquetzal** [comment]
Sorry I forgot: 
You should do those lines **before** importing cdlib.
Check that example (the content is not important, it was created as a support of an unrelated discussion)
https://colab.research.google.com/drive/1li-kNa7BGp5HjSpa0MB2f2Pi3CL7IZn4

**Comment by shirleykq-zhang** [comment]
Thank you! It works perfectly.

**Comment by revantshah24** [comment]
It is not working for me I am not sure why.

**Comment by Tanzina-Sultana** [comment]
Mee to followed provided research steps
