### ISSUE TITLE
ZeroDevisionError in Expectation Maximization Community Algorithm

### ISSUE THREAD

**Issue by OUStudent** [GiulioRossetti/cdlib#194]
Trying to use `em`  function to find communities in my undirected networkx Graph. 

Line 31 in algorithms\internal\em.py there is a 
`q[i][g] /= norm`, which throws a division by zero error. Looking at the source code of the `e_step` function:

```
    def e_step(self, q):
        for i in range(self.n):
            q.append([])
            norm = 0.0
            for g in range(self.k):
                x = self.pi[g]
                for j in self.g.neighbors(i):
                    x *= self.theta[g][j]
                q[i].append(x)
                norm += x
            for g in range(self.k):
                q[i][g] /= norm         # error occurs here
```

Norm is only updated on `norm += x`, where x is updated in the for loop by `x *= self.theta[g][j]`. I debugged the code and found that for in the third inner for loop `for j in self.g.neighbors(i):` there were 168 neighbors, meaning this node had 168 edges; the problem is that `self.theta[g] `for the node initialized all 168 values to random numbers around 0.0005, meaning that x is updated by repeatedly multiplying itself by numbers around 0.0005 . In this way, 0.0005 ^ 168 = 0.

I suggest changing the initialization of theta based off the number of edges a node has or not divide by norm if it is zero.

**Comment by samO2I1** [comment]
Hi @GiulioRossetti !! I am new to Google Summer Of Code. Can I work on this issue?

**Comment by GiulioRossetti** [comment]
@samO2I1 if you would like to work on it that's perfectly fine! 

We didn't have had contributors so far from the Google summer of code program: is there something we need to do to formally accept your contribution? Feel free to write me an email with all the details.

**Comment by samO2I1** [comment]
@GiulioRossetti can I get your email address

**Comment by GiulioRossetti** [comment]
@samO2I1 you can find all contacts you need in my profile ;)
