### ISSUE TITLE
Louvain on google colab

### ISSUE THREAD

**Issue by Yquetzal** [GiulioRossetti/cdlib#195]
For some reasons, I cannot use Louvain when working from google colab.
Error:
```AttributeError: module 'community' has no attribute 'best_partition'```

it seems an issue with a pre-installed version of python-louvain, since basically I cannot use this module in google Colab, even outside of cdlib.

To make it work, I must use 
```import community.community_louvain as cl```
instead of ``import community as cl```

Not sure why, since it was working before...

And if I force uninstall and force re-install python-louvain, then everything works as expected.

I'll continue to investigate tonight, since usually I use this setting in my teaching...

**Comment by GiulioRossetti** [comment]
It seems related to https://github.com/GiulioRossetti/cdlib/issues/193#issuecomment-968725433

**Comment by Yquetzal** [comment]
Solved in principle with the latest version
