### ISSUE TITLE
I cannot config spins parameter on spin glass algorithm. Now the spin is fix at 25. How can I config that parameter, please?

### ISSUE THREAD

**Issue by omoanemo** [GiulioRossetti/cdlib#197]
Please use the following template to describe your feature request.
Feel free to remove those sections that do not apply to your specific request.

**Is your feature request related to a problem? Please describe.**

**Reference.**
In case of an algorithm/quality function/visualization:
- the paper(s) in which the requested feature has been introduced,
- an exsiting python implementation of the feature (if available).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GiulioRossetti** [comment]
Fix integrated into https://github.com/GiulioRossetti/cdlib/commit/e7025b1f0c635f92a64c86148f776ced313be36d
