### ISSUE TITLE
Expansion metric seems incorrect

### ISSUE THREAD

**Issue by shakebeforeuse** [GiulioRossetti/cdlib#198]
There seems to be some kind of inconsistency between documentation and implementation of Expansion (fitness function).

- Documentation: number of community nodes divided by number of edges trespassing community boundary [(link)](https://cdlib.readthedocs.io/en/latest/reference/eval/cdlib.evaluation.expansion.html#cdlib.evaluation.expansion)
- Implementation: `float(edges_outside)/ns`

I can submit a pull request however I do not think that the reference is correct either. ANS paper agrees with the documentation (https://doi.org/10.1007/s41109-019-0165-9).

**Comment by GiulioRossetti** [comment]
It seems that the issue is on the docs where the definition of Cs and Ns are swapped. Expansion is the ratio of community outgoing edges w.r.t. the number of community nodes.

**Comment by GiulioRossetti** [comment]
A "master" reference for the definitions of the majority of CDlib fitness functions:

Yang, Jaewon, and Jure Leskovec. 
"Defining and evaluating network communities based on ground-truth." 
Knowledge and Information Systems 42.1 (2015): 181-213.

There you can also find the attribution of such measure to the paper cited in the documentation.
