### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by williballenthin** [GiulioRossetti/cdlib#200]
Would you please clarify the licensing of this project? I see this is listed as BSD-2; however, the library seems to rely on GPL dependencies (igraph). What parts of cdlib are BSD-2 vs GPL (vs other license)?

Context:
I am looking for a walktrap implementation that I can use in a non-GPL project (likely Apache 2). The original C++ walktrap implementation is GPL, as is the version embedded with igraph. I was excited to see that BSD-2 cdlib provides a walktrap implementation; however, upon inspection, I see that it simply invokes igraph (GPL). Therefore, I understand (IANAL) cannot use cdlib walktrap in an Apache2 project.

  1. would you agree with this understanding?
  2. can you recommend any Apache2-compatible implementations of walktrap?

**Comment by GiulioRossetti** [comment]
Hi,
CDlib main codebase is released under BSD-2: this means all the clustering objects, fitness functions, benchmarking and reimplemented CD algorithms (as a rule of thumb, most of/all CD algorithms that are  under the "algorithms/internal" folder). 

The remaining part of the library can be seen as an interface toward external dependencies. To access those functionalities the licences are inherited by the original projects.

Unfortunately, I'm not aware of Apache2 (or fully compatible) walktrap implementations.
