### ISSUE TITLE
Import issue on Mac M1

### ISSUE THREAD

**Issue by dummyindex** [GiulioRossetti/cdlib#201]
**Describe the bug**
`import cdlib.algorithms`
Apple M1 chip

```
(dynamo-dev) Ks-MacBook-Pro:dynamo-tutorials random$ python
Python 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cdlib
>>> import cdlib.algorithms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/random/opt/anaconda3/envs/dynamo-dev/lib/python3.9/site-packages/cdlib/algorithms/__init__.py", line 2, in <module>
    from .crisp_partition import *
  File "/Users/random/opt/anaconda3/envs/dynamo-dev/lib/python3.9/site-packages/cdlib/algorithms/crisp_partition.py", line 2, in <module>
    import infomap as imp
  File "/Users/random/opt/anaconda3/envs/dynamo-dev/lib/python3.9/site-packages/infomap.py", line 35, in <module>
    import _infomap
ImportError: dlopen(/Users/random/opt/anaconda3/envs/dynamo-dev/lib/python3.9/site-packages/_infomap.cpython-39-darwin.so, 0x0002): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/random/opt/anaconda3/envs/dynamo-dev/lib/python3.9/site-packages/_infomap.cpython-39-darwin.so
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)
```

```
(cdlib-test) Ks-MacBook-Pro:16725-medical-imaging random$ python
Python 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:36:06) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cdlib
>>> import cdlib.algorithms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/random/opt/anaconda3/envs/cdlib-test/lib/python3.8/site-packages/cdlib/algorithms/__init__.py", line 2, in <module>
    from .crisp_partition import *
  File "/Users/random/opt/anaconda3/envs/cdlib-test/lib/python3.8/site-packages/cdlib/algorithms/crisp_partition.py", line 2, in <module>
    import infomap as imp
  File "/Users/random/opt/anaconda3/envs/cdlib-test/lib/python3.8/site-packages/infomap.py", line 35, in <module>
    import _infomap
ImportError: dlopen(/Users/random/opt/anaconda3/envs/cdlib-test/lib/python3.8/site-packages/_infomap.cpython-38-darwin.so, 0x0002): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/random/opt/anaconda3/envs/cdlib-test/lib/python3.8/site-packages/_infomap.cpython-38-darwin.so
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)

```
**To Reproduce**
installed via pip
```
Name: cdlib
Version: 0.2.5
Summary: Community Discovery Library
Home-page: https://github.com/GiulioRossetti/cdlib
Author: Giulio Rossetti
Author-email: giulio.rossetti@gmail.com
License: BSD-Clause-2
Location: /Users/random/opt/anaconda3/envs/cdlib-test/lib/python3.8/site-packages
Requires: angel-cd, bimlpa, chinese-whispers, cython, demon, dynetx, eva-lcd, future, infomap, karateclub, leidenalg, markov-clustering, matplotlib, networkx, nf1, numpy, pandas, pooch, pulp, pyclustering, python-igraph, python-Levenshtein, python-louvain, scikit-learn, scipy, seaborn, thresholdclustering, tqdm, wurlitzer
```
- Operating System
  - macOS Monterey
- Python version
 - tried in conda env 3.7, 3.8, 3.9

**Expected behavior**
Import successfully (cdlib worked and tested in 2021)

I treid `brew install libomp` but it does not work. The laptop is relatively new (released last year) and there are almost no messy system level customizations on this laptop.

Thanks for providing the community with the package! It is convenient, powerful and with good documentation.

**Comment by GiulioRossetti** [comment]
Thanks for raising this issue: unfortunately, I don't have a recent M1 MacOS to reproduce it... 

@Yquetzal can you look into this?

**Comment by Yquetzal** [comment]
I'll look into it, Wednesday at the later.

**Comment by Yquetzal** [comment]
So I confirm that I have the same problem, and I could not find a simple solution to solve the problem. It comes from infomap itself. I'll inform the creators of infomap of this problem just now, but in the meantime I have no solution... @GiulioRossetti , I was thinking even before this that we should have as default version a very basic, python-only cdlib (no infomap, no Leiden, no karate). 1)Many people come for Louvain and quality functions, 2) it would be lighter to install for teaching, 3)When such a crash happen, people will understand that it comes from the imported package. What do you think ? I can participate to clean the error messages when people try to run a method nor already installed.

**Comment by GiulioRossetti** [comment]
@Yquetzal I think that having a "light" version of CDlib should be easy to achieve (we already have something similar with the pip package). If you can spot all the "troubling" dependencies I'll take care of revising the packaging pipeline and updating the installation instructions.

**Comment by Yquetzal** [comment]
@dummyindex Following your problem, we modified the library structure so that you are not blocked by external packages that cannot install on your architecture. So now cdlib should work, you just cannot use infomap. I reported the problem to infomap managers, if you need it you can go to their GitHub and see that current workaround they propose, hopefully there is a simpler solution soon.
Feel free to report any additional issue.
