### ISSUE TITLE
`infomap` ImportError not catched by `cdlib` in [crisp_partition.py, bipartite_clustering.py] in light version

### ISSUE THREAD

**Issue by dummyindex** [GiulioRossetti/cdlib#204]
Hi cdlib team,

Thanks for fixing the import issue mentioned in #201 . There is probably one more little code issue to be fixed.

**Describe the bug**
```
try:
    import infomap as imp
except ModuleNotFoundError:
    missing_packages.add("infomap")
    imp = None
```
This does not catch `ImportError`, which is the case in my environment. After capturing Exception (all exception) in `crisp_partition.py, bipartite_clustering.py` (two files), I can import cdlib.algorithms without other issues.

**To Reproduce**
- CDlib version
0.2.6 light version

**Screenshots**
![image](https://user-images.githubusercontent.com/12120524/160213574-5b2d6f19-d101-4854-b219-f5dbb2da4c0d.png)

**Comment by Yquetzal** [comment]
Thanks for the fix and code cleaning, @GiulioRossetti the pull request seems OK to me...
