### ISSUE TITLE
Make use of "weights" parameter while using ensemble.pool

### ISSUE THREAD

**Issue by udiallo** [GiulioRossetti/cdlib#210]
I want to compare different cd algorithms using the ensemble.pool function. However, as configuration parameter there are only the **ensemble.Parameter** and **ensemble.BoolParameter** available. 

Is there a way to include the "weights" parameter of algorithms such as leiden? Normally it looks like that:

    `partition = algorithms.leiden(G, weights="weight")`

It seems that a string parameter cannot be used when using ensemble.pool.

Thanks in advance.

**Comment by GiulioRossetti** [comment]
Hi, thanks for opening this issue.
I'll work on it next week, it should be easy to implement.
