### ISSUE TITLE
a mistaken parameter in conga

### ISSUE THREAD

**Issue by kentechx** [GiulioRossetti/cdlib#215]
https://github.com/GiulioRossetti/cdlib/blob/27eeef474c023c3cf453c4d21aa9ceed465411f4/cdlib/algorithms/overlapping_partition.py#L666

should be
```python
communities = Conga_(g, number_communities) 
```

**Comment by GiulioRossetti** [comment]
Thanks, the issue has been addressed and the fix pushed to master.
