### ISSUE TITLE
BIMLPA KeyError when using igraph object 

### ISSUE THREAD

**Issue by FrancescoDiCursi** [GiulioRossetti/cdlib#219]
**Describe the bug**
- When using an igraph object with BIMPLA it raises a **KeyError**: the library needs a "biparatite" arg for partitions whereas igraph uses "type" as default arg.
- Even with the aforementioned change the **KeyError** doesn't disappear: one needs both to change the attribute name and convert igraph to networkx in order to resolve the error.

**To Reproduce**
Use a bipartite igraph object as arg in BIMPLA

**Expected behavior**
It should handle igraph objects (automatically or by a further specification through an additional arg) 

**Screenshots**
![thumbnail_image](https://user-images.githubusercontent.com/79453817/234858095-4cd7ec77-5b19-446c-b152-07fba5b7163f.png)

![thumbnail_image](https://user-images.githubusercontent.com/79453817/234858126-add154dd-4295-4317-a8fd-3cff71ea8609.png)

**Comment by GiulioRossetti** [comment]
The conversion function requires an `igraph.Graph` object rather than an `igraph.Bipartite` one.
