### ISSUE TITLE
Visualize the Top N communities

### ISSUE THREAD

**Issue by EricJoung1997** [GiulioRossetti/cdlib#230]
Is it possible to only visualize the Top N communities? because my network detected a large number of communities (approximately 7000)

**Comment by amineitji** [comment]
This code creates a new graph (subgraph) containing only the nodes from the top N communities and then visualizes this subgraph.  You can adjust the top_n variable to change the number of top communities to display.

`import networkx as nx

import matplotlib.pyplot as plt



def greedy_modularity_community_detection(graph):

communities = list(nx.community.greedy_modularity_communities(graph))

return [list(community) for community in communities]



# Create a synthetic graph

G = nx.karate_club_graph()



# Run greedy modularity community detection

detected_communities = greedy_modularity_community_detection(G)



# Sort communities by size in descending order

sorted_communities = sorted(detected_communities, key=lambda x: len(x), reverse=True)



# Define the number of top communities to show

top_n = 3



# Show the top N communities

print(f"Top {top_n} Communities:")

for i in range(min(top_n, len(sorted_communities))):

print(f"Community {i + 1}: {sorted_communities[i]}")



# Create a new graph with only nodes from the top N communities

top_n_nodes = [node for community in sorted_communities[:top_n] for node in community]

subgraph = G.subgraph(top_n_nodes)



# Visualize the subgraph with top communities colored

pos = nx.spring_layout(subgraph)

colors = [0] * len(subgraph.nodes)

for i, community in enumerate(sorted_communities[:top_n]):

for node in community:

colors[node] = i + 1



nx.draw(subgraph, pos, node_color=colors, with_labels=True)

plt.show()

`

**Comment by amineitji** [comment]
``import x``

**Comment by amineitji** [comment]
This code creates a new graph (subgraph) containing only the nodes from the top N communities and then visualizes this subgraph. You can adjust the top_n variable to change the number of top communities to display.

`` 
import networkx as nx

import matplotlib.pyplot as plt



def greedy_modularity_community_detection(graph):

communities = list(nx.community.greedy_modularity_communities(graph))

return [list(community) for community in communities]



# Create a synthetic graph

G = nx.karate_club_graph()



# Run greedy modularity community detection

detected_communities = greedy_modularity_community_detection(G)



# Sort communities by size in descending order

sorted_communities = sorted(detected_communities, key=lambda x: len(x), reverse=True)



# Define the number of top communities to show

top_n = 3



# Show the top N communities

print(f"Top {top_n} Communities:")

for i in range(min(top_n, len(sorted_communities))):

print(f"Community {i + 1}: {sorted_communities[i]}")



# Create a new graph with only nodes from the top N communities

top_n_nodes = [node for community in sorted_communities[:top_n] for node in community]

subgraph = G.subgraph(top_n_nodes)



# Visualize the subgraph with top communities colored

pos = nx.spring_layout(subgraph)

colors = [0] * len(subgraph.nodes)

for i, community in enumerate(sorted_communities[:top_n]):

for node in community:

colors[node] = i + 1



nx.draw(subgraph, pos, node_color=colors, with_labels=True)

plt.show() ``

**Comment by amineitji** [comment]
## This code creates a new graph (subgraph) containing only the nodes from the top N communities and then visualizes this subgraph. You can adjust the top_n variable to change the number of top communities to display.


```python
import networkx as nx
import matplotlib.pyplot as plt

def greedy_modularity_community_detection(graph):
    communities = list(nx.community.greedy_modularity_communities(graph))
    return [list(community) for community in communities]

# Create a synthetic graph
G = nx.karate_club_graph()

# Run greedy modularity community detection
detected_communities = greedy_modularity_community_detection(G)

# Sort communities by size in descending order
sorted_communities = sorted(detected_communities, key=lambda x: len(x), reverse=True)

# Define the number of top communities to show
top_n = 3

# Show the top N communities
print(f"Top {top_n} Communities:")
for i in range(min(top_n, len(sorted_communities))):
    print(f"Community {i + 1}: {sorted_communities[i]}")

# Create a new graph with only nodes from the top N communities
top_n_nodes = [node for community in sorted_communities[:top_n] for node in community]
subgraph = G.subgraph(top_n_nodes)

# Visualize the subgraph with top communities colored
pos = nx.spring_layout(subgraph)
colors = [0] * len(subgraph.nodes)
for i, community in enumerate(sorted_communities[:top_n]):
    for node in community:
        colors[node] = i + 1

nx.draw(subgraph, pos, node_color=colors, with_labels=True)
plt.show()
```

**Comment by amineitji** [comment]
You can focus on visualizing only the top communities by utilizing the top_k parameter in the plot_network_clusters and plot_community_graph functions. This parameter allows you to specify the number of top communities you want to visualize. 

```python
# Assuming 'g' is your graph and 'coms' is the partition mapping nodes to communities
viz.plot_community_graph(g, coms, top_k=5)
