### ISSUE TITLE
A request to have initial_membership as an input parameter in the Louvain algorithm

### ISSUE THREAD

**Issue by Praveer1981** [GiulioRossetti/cdlib#231]
Hi, 
I am a new user of CDlib. Currently, I am studying community detection in social networks. As we know, Louvain and Leiden are the best-known algorithms in this field, and this library provides the APIs to use both methods.

**Is your feature request related to a problem? Please describe.**

I see that the `leiden` function takes `initial_membership` as a second parameter.However, the `Louvain` does note take the `initial_membership` as input paramter. which means that Louvain always starts from the singleton partition.

I think Louvain should also take `initial_membership` as an input parameter to avoid starting from the singleton partition.

**Reference.**
[Leiden](https://github.com/GiulioRossetti/cdlib/blob/master/cdlib/algorithms/crisp_partition.py#L563)
[Louvain](https://github.com/GiulioRossetti/cdlib/blob/master/cdlib/algorithms/crisp_partition.py#L494)

**Describe the solution you'd like**
Pass `initial_membership` as a parameter to the louvain.

`def louvain(
    g_original: object,
     **initial_membership: list = None**
    weight: str = "weight",
    resolution: float = 1.0,
    randomize: int = None,
) -> NodeClustering:`

**Comment by GiulioRossetti** [comment]
Hi, 
for both Louvain and Leiden we rely on third party implementations. I'll check if the Louvain one(s) also supports initial clusters assignment.

By the way, I will not say that they are the "best" algorithms out there for several reasons - the simplest one being the fact that community detection is an ill-posed problem...

Let's say they are probably the most used ones, that's a completely different story :wink:

**Comment by Praveer1981** [comment]
Hi @GiulioRossetti  Thanks for your response. I, too, have a similar understanding of both algorithms. But I am experimenting with a few things to improve the modularity of the partition. I see that the Louvain function calls  [community_louvain.best_partition](https://github.com/GiulioRossetti/cdlib/blob/master/cdlib/algorithms/crisp_partition.py#L541), which takes `partition` as 2nd parameter. But, actually `louvain` function does not take the same as input parameter.

**Comment by Praveer1981** [comment]
I wnated to have a PR, but I do not have permission to create PR in this repo.

**Comment by GiulioRossetti** [comment]
@Praveer1981 that's strange... The repo doesn't have particular restrictions on proposing PRs. We handled several of them by external contributors in the past..

**Comment by Praveer1981** [comment]
@GiulioRossetti  I raised a PR#[232](https://github.com/GiulioRossetti/cdlib/pull/232)

**Comment by GiulioRossetti** [comment]
Related PR #232 integrated in master

**Comment by Praveer1981** [comment]
@GiulioRossetti  Thanks!
