### ISSUE TITLE
wCommunity always returns one community

### ISSUE THREAD

**Issue by jade-bejide** [GiulioRossetti/cdlib#233]
**Describe the bug**
Code:
```python
import networkx as nx
from cdlib import algorithms
import numpy as np

graph = nx.complete_graph(100)
for node_i, node_j in graph.edges:
    graph[node_i][node_j]["weight"] = np.random.normal(20, 5)
communities = algorithms.wCommunity(graph, min_bel_degree=0.6, threshold_bel_degree=0.6).communities
print(len(communities))
```

For the following code, ```algorithms.wCommunity``` always returns a single community whereas ```algorithms.louvain``` returns around five. Is there a recommended tolerance so to better detect sub communities?

**To Reproduce**
- CDlib version: 0.3.0
- Operating System Windows
- Python version 3.11
- Version(s) of CDlib required libraries

**Expected behavior**
The algorithm should return at least as many communities as Louvain.

**Comment by GiulioRossetti** [comment]
Given that you're applying CD to a complete graph the worrisome result is the one of Louvain, not the one of wCommunity...

**Comment by jade-bejide** [comment]
Hi @GiulioRossetti, thank you for the response. For further context, this is regarding extensions of a existing paper as part of my academic study where the weights are updated via simulation. The end result is that some edge weights are zero and others are relatively larger (ie 40-50) such that in essence the zero weighted edges mean that the graph is longer complete. Would you statement still apply in this context?

**Comment by GiulioRossetti** [comment]
Well, considering that the vanilla version of Louvain doesn't consider edge weights if you don't explicitly remove the 0-weigthed ones from the graph object my statement still applies.

I am not sure if wCommunity assumes edges with weight=0 as non existent or if it requires them to be explicitly removed. If I were you I'll try both configurations and compare the results... you know, just in case.

**Comment by jade-bejide** [comment]
I see, I'll investigate this further independently. Thanks for the help.
