### ISSUE TITLE
TemporalClustering() appears to be adding new snapshots to existing structure (comparable to TILES without edge removal)

### ISSUE THREAD

**Issue by masonyoungblood** [GiulioRossetti/cdlib#236]
Hello! I am using `CDLIB` for dynamic community detection, and I'm running into odd behavior where snapshots are added to the existing structure in a cumulative fashion (comparable to `TILES` without edge removal). Do you know what the issue might be, or is this the expected behavior? Here is the code I'm using:

```
for f in files:
    tc = TemporalClustering()
    for t in years:
        g = networkx.read_edgelist(path + "dyncomm_input/" + f + "/" + str(t + min_year) + ".csv", delimiter = ", ")
        coms = algorithms.louvain(g)
        tc.add_clustering(coms, t)
    matches = tc.community_matching(jaccard)
    tc.add_matching(matches)
```

I have confirmed that it's not an issue with how the edgelists are constructed, and it happens across multiple clustering algorithms (e.g., `louvain`, `infomap`, `label_propagation`).

**Comment by GiulioRossetti** [comment]
That's strange I'll look into it as soon as possible and let you know. Thanks for raising the issue!

**Comment by masonyoungblood** [comment]
Actually it looks like it may actually be an issue with my edgelist construction! I'll look into it right now.

**Comment by GiulioRossetti** [comment]
@masonyoungblood let me know if you have updates on the subject

**Comment by masonyoungblood** [comment]
Yes I figured it out and it was an issue with my code - Thanks again for your quick response!
