### ISSUE TITLE
Contribute with clustering algorithm

### ISSUE THREAD

**Issue by seoanezonjic** [GiulioRossetti/cdlib#239]
Hi @GiulioRossetti
I have been using  CDLIB for several years and it's  my first option when I have to clusterize a network. CDlib is a great tool and I hope to use it for many years. Rigth now, I'm working with large networks and I was interested to apply the HLC algorithm due to the necessities of my project. My problems are:
* HLC implemented in CDLIB cannot handle weigths (but the picked implementation has code for it and I have activate it)
* HLC no implements the exact description of Ahn et al
* The implementation it's not optimized for large networks.

Due to these problems, I have forked cdlib and implemented additional HLC in the following ways:
* HLC_w: Activates weighted networks in cdlib's original code
* HLC_f: New implementation that handles binary and weighted networks using numpy and scipy . It's a lot faster that original implementation and follows the Ahn's paper description.

The code is  [here](https://github.com/seoanezonjic/cdlib) . I want to contribute to CDLIB but I'm not sure how to make a correct pull request.
Thank you in advance
Pedro Seoane

**Comment by GiulioRossetti** [comment]
Thanks for the contribution!
I generated the PR #240 - as soon as the test are ok I'll proceed with the integration in the master branch.

Best,
Giulio
