### ISSUE TITLE
Unable to perform grid search for fluid asyn community detection algo

### ISSUE THREAD

**Issue by ashuein** [GiulioRossetti/cdlib#70]
I am trying to do a grid search for async fluid community detection method using the following commands

`import networkx as nx`
`from cdlib import algorithms, ensemble,evaluation`
`G = nx.karate_club_graph()`
`k = ensemble.Parameter(name='k',start=5,end=20,step=1)`
`com_flud,scor_louv = ensemble.grid_search(graph=G,method=algorithms.async_fluid,parameters=[k],quality_score=evaluation.erdos_renyi_modularity,aggregate=max)`

But when trying to execute it, I get the following error:

` File "/usr/local/lib/python3.6/dist-packages/networkx/algorithms/community/asyn_fluid.py", line 74, in asyn_fluidc
    raise NetworkXError("k must be an integer.")`

`NetworkXError: k must be an integer.
`
I don't understand this error as the start, end and step all are integers then why I get this error?

**Comment by GiulioRossetti** [comment]
Bug identified and fixed. 
the parameter generator was generating ranges of numpy.int64 values instead of int ranges.

Thanks for reporting!
You can find the bugfix implemented in the github repository: it will be integrated in the pypl package in the next minor release.
