### ISSUE TITLE
Package dependencies pegged to minor versions

### ISSUE THREAD

**Issue by epatters** [GiulioRossetti/cdlib#72]
Thanks for the useful package.

Like presumably most users of this package, I use Anaconda. When I install the package through pip (`pip install cdlib`), it tries to replace core Anaconda packages such as scipy and pandas with slightly different versions. To avoid that, I installed with `--no-deps` and manually got the dependencies I needed. The package works, but I still get warnings from pip:
```
$ pip check
cdlib 0.1.7 requires sphinx, which is not installed.
cdlib 0.1.7 requires sphinx-rtd-theme, which is not installed.
cdlib 0.1.7 has requirement matplotlib==3.1.0, but you have matplotlib 3.1.1.
cdlib 0.1.7 has requirement pandas==0.24.2, but you have pandas 0.25.1.
cdlib 0.1.7 has requirement scipy==1.3.0, but you have scipy 1.3.1.
cdlib 0.1.7 has requirement tqdm==4.32.2, but you have tqdm 4.32.1.
```

The dependencies should probably not be specified so exactly.

**Comment by GiulioRossetti** [comment]
Thanks for your interest in cdlib.

I've updated the requirements.txt file (#74): now packages minor versions are not specified.
