### ISSUE TITLE
Request to loosen package dependencies as much as possible

### ISSUE THREAD

**Issue by tedhchen** [GiulioRossetti/cdlib#79]
Hi there, 

Thank you for the useful package! 

I know you have removed the requirement for minor package versions in an earlier issue (https://github.com/GiulioRossetti/cdlib/issues/72#issue-490429466), but I was wondering if the requirements can be further loosened in general?

We're trying to install the package on the department server, and when we do so, it downgrades a number of the other packages. Because the requirements are a bit restrictive right now, it is preventing us from using it widely.

Thank you for considering this.

Best,
Ted

**Comment by GiulioRossetti** [comment]
Hi,
no problem with that: I'll explore this within next week.

Best,
Giulio

**Comment by tedhchen** [comment]
Great. Thank you.

-Ted

**Comment by Yquetzal** [comment]
@GiulioRossetti what do you think, since it is a downgrade problem usually, we could just replace all the == by >= and it should do the trick, right?

**Comment by GiulioRossetti** [comment]
More or less: we have to identify the lowest version requirements that don't break the installation.

**Comment by GiulioRossetti** [comment]
@tedhchen just as a temporary fix, have you tried to install the library on a fresh conda/pip environment? 

Doing so you should be able to avoid breaking the preexisting python packages server configuration (and can be done in user space).

**Comment by Yquetzal** [comment]
> More or less: we have to identify the lowest version requirements that don't break the installation.
Ok, you want to do it the clean way ;) My solution can also be a quick fix, 90% of people don't mind upgrading but most people don't want to downgrade...

**Comment by GiulioRossetti** [comment]
@Yquetzal actually I was thinking exactly to implement your solution, with the only caveat of  getting a more conservative lower version for the required dependencies :-)

**Comment by Yquetzal** [comment]
For reference, errors appearing when installing on google colab:
ERROR: pandas 0.25.1 has requirement python-dateutil>=2.6.1, but you'll have python-dateutil 2.5.3 which is incompatible.
ERROR: google-colab 1.0.0 has requirement pandas~=0.24.0, but you'll have pandas 0.25.1 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.

**Comment by GiulioRossetti** [comment]
Mmm a few of such dependencies are not from cdlib but from packages it import... The dependencies nightmare begins...

**Comment by tedhchen** [comment]
@GiulioRossetti, thanks for the suggestion. I am using the package in a fresh environment for now.

**Comment by Yquetzal** [comment]
Well on the other side if we just remove all versions requirements, everything install without problem on google colab. (well we need to keep the networkx version limit at least, but appart from that we could accept anything apriori, and re-add limits if users encounter problems...)

**Comment by GiulioRossetti** [comment]
I've merged a branch (#75 ) containing, among other stuff, a revised requirements.txt with loose dependencies. 

@tedhchen  Could you check if this setup works for you?
If not, which are your critical dependencies that I have to check for?

**Comment by GiulioRossetti** [comment]
> Well on the other side if we just remove all versions requirements, everything install without problem on google colab. (well we need to keep the networkx version limit at least, but appart from that we could accept anything apriori, and re-add limits if users encounter problems...)

Yes that's an alternative solution, but I would like to have some meaningful boundaries... 
Moreover, for networkx now we have both a minimum version (>=2.1) and a maximum one (<2.4): the last release breaks a lot of stuff for a very stupid reason (they decided to rename the graph field _node_ in _nodes_ )

**Comment by tedhchen** [comment]
Thanks, @GiulioRossetti and @Yquetzal, for working on this. The loosened dependencies make things easier. There's nothing critical for us at the moment.

**Comment by rkdarst** [comment]
I'm installing cdlib in a generic conda environment in a cluster, and also have issues with the dependencies (actually, I know @tedhchen, it's why this was originally started).  We were recently upgrading our automatic anaconda installation, so was checking requiremnts here.  I see these pins or max-versions:
```
mock==3.0.*
sphinx==1.7.5 # pyup: ignore
networkx>=2.2, <2.4
python-louvain==0.13
pulp==1.6.*
pquality==0.0.7
infomap==1.0.0b47
python-igraph==0.7.1.post6
leidenalg==0.7.0
angel-cd==1.0.2
```

Which is recommended for a environment for a project, but when it may be combined with arbitrary other packages, we're eventually going to get conflicts, and if these versions stop being updated, eventually will be breaking the environment.  So, could the non-essential dependencies be relaxed even further?  Of course, maybe stuff is too unstable for this to really work, in which case I understand.

We try to install "everything that might be useful to anyone, if it's mutually compatible with everyone else".  Not everything works like this, but would be nice to have cdlib here by default.

**Comment by GiulioRossetti** [comment]
Hi,
Could you provide some additional information on the packages in the requirements for which you have conflicts (required version vs. installed one)?

I'm sure we can at least try to find a middle ground: the only ones in the list you posted that seems troubling to me are infomap, python-igraph and, to some extent, networkx.

**Comment by rkdarst** [comment]
Right now, it did install, but with some downgrades.  I'm more thinking for years in the future, when a problem comes up: everything installed at once with our automatic system (before, a manual installation downgraded deps, which could be upgraded later), so dependency resolution can take a long time, and the error messages aren't that good to figure out the problem packages.

The hard dependency on sphinx is a problem, mock too.  Both of these have advanced a lot.

The CD algorithm packages aren't likely to be used by other things, but who knows.

Anyway, these are just observations I thought I would follow up on.  This is a reasonable case to recommend people to install in a virtualenv, so don't worry too much.

**Comment by GiulioRossetti** [comment]
Ok, I see the issue.
I removed the mock and sphinx dependencies: they are not needed by the final user, only by external tools (mainly travis). I'll include the fix in the next pypi release. Thanks!
