### ISSUE TITLE
Leiden algorithm parameter?

### ISSUE THREAD

**Issue by nikhilmjn** [GiulioRossetti/cdlib#80]
The leiden algorithm implementation (https://github.com/vtraag/leidenalg) by the developer provides for a resolution parameter, but your implementation does not seem to.

Why is that? Am I missing something?

**Comment by GiulioRossetti** [comment]
Thanks for opening this issue. I'll look into it next week.

It is likely that the the Leiden resolution parameter was wrongly forgotten while implementing the cdlib wrapper.

**Comment by GiulioRossetti** [comment]
I've checked the Leiden APIs: [ModularityVertexPartition](https://leidenalg.readthedocs.io/en/latest/reference.html#leidenalg.ModularityVertexPartition) partition_type does not allow to specify the resolution parameter, that's the reason we didn't implement it in cdlib. 

If you change the partition type (e.g., using [CPMVertexPartition](https://leidenalg.readthedocs.io/en/latest/reference.html#cpmvertexpartition)) this behavior changes - as correctly reflected also by the cdlib APIs.

**Comment by chansigit** [comment]
> 

I think leidenalg can alter resolution via kwargs, a bioinformatic package scanpy has leiden algorithm calling it.

https://github.com/scverse/scanpy/blob/bd06cc3d1e0bd990f6994e54414512fa0b25fea0/scanpy/tools/_leiden.py#L142

https://github.com/scverse/scanpy/blob/master/scanpy/tools/_leiden.py

will you consider adding it in cdlib?
