### ISSUE TITLE
Example for leiden community detection with edge weights

### ISSUE THREAD

**Issue by richardehughes** [GiulioRossetti/cdlib#82]
I have tried using the leiden algorithm with edge weight and have not been able to figure it out.   Can you provide an example or tell me what I am doing wrong?

To use weight with Louvain, one simply does this:
   louvain_coms = algorithms.louvain(g, weight='weight', resolution=0.1, randomize=False)
where 'weight' is an edge property (I am using network to build the initial graph g).  This works.

When I try this with leiden, I get this error:
      leiden_coms = algorithms.leiden(g, weights='weight')

I get the error below.   Can you help me see what I am doing wrong?

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-28-35144237d13f> in <module>
----> 1 leiden_coms = algorithms.leiden(g, weights='weight')
      2 comms = leiden_coms.communities
      3 overlap = leiden_coms.overlap
      4 print("overlap",overlap)
      5 commNum = 0

~/.local/lib/python3.6/site-packages/cdlib/algorithms/crisp_partition.py in leiden(g, initial_membership, weights)
    368 
    369     part = leidenalg.find_partition(g, leidenalg.ModularityVertexPartition,
--> 370                                     initial_membership=initial_membership, weights=weights
    371                                     )
    372     coms = [g.vs[x]['name'] for x in part]

~/.local/lib/python3.6/site-packages/leidenalg/functions.py in find_partition(graph, partition_type, initial_membership, weights, n_iterations, seed, **kwargs)
     82   partition = partition_type(graph,
     83                              initial_membership=initial_membership,
---> 84                              **kwargs)
     85   optimiser = Optimiser()
     86 

~/.local/lib/python3.6/site-packages/leidenalg/VertexPartition.py in __init__(self, graph, initial_membership, weights)
    448     if weights is not None:
    449       if isinstance(weights, str):
--> 450         weights = graph.es[weights]
    451       else:
    452         # Make sure it is a list

KeyError: 'Attribute does not exist'

**Comment by richardehughes** [comment]
I discovered that if I instead make the graph using igraph instead of networkx (with the same node and edge attributes) the leiden method with edge weights works fine.

**Comment by Yquetzal** [comment]
The corrected conversion should solve the problem, thanks !
