### ISSUE TITLE
KeyError with frc_fgsn

### ISSUE THREAD

**Issue by deklanw** [GiulioRossetti/cdlib#91]
Getting a KeyError here:
https://github.com/GiulioRossetti/cdlib/blob/master/cdlib/algorithms/internal/FuzzyCom.py#L81

Isn't this line assuming that the graph is connected (in the undirected case) or strongly connected (in the directed case)?

I changed the line to

```python
            if j in n_dist and n_dist[j] <= r:
```

and it doesn't throw, but I haven't checked if the results make sense yet.

**Comment by GiulioRossetti** [comment]
Yes, in this case, it seems that the authors assumed the connectedness of the graph.
If your results checked out and everything works as it should feel free to open a pull request with the fix.

**Comment by Yquetzal** [comment]
Seems coherent with the code, the matrix is initialized with zeros, so if the distance is infinite, the value stay at zero... @deklanw can you open a pull request with your improvement? Otherwise, I can do it.

**Comment by deklanw** [comment]
@Yquetzal sure. still haven't validated the results in any way but if you all think it makes sense
