### ISSUE TITLE
Candidates for inclusion

### ISSUE THREAD

**Issue by deklanw** [GiulioRossetti/cdlib#93]
I'm just posting this here in case anyone hasn't seen it

https://github.com/benedekrozemberczki/awesome-community-detection

I don't have the background to evaluate which of these are good, but searching for "Python Reference" on the page gives 101 results

**Comment by Yquetzal** [comment]
Thanks for the suggestion, great reference list! Any help welcomed ;)

**Comment by DonaldTsang** [comment]
@deklanw take a look at these, is it possible to list down the newer versions of Community Detection?
- https://www.semanticscholar.org/paper/Network-Community-Detection-on-Metric-Space-Saha-Ghrera/9487175c52387349da28243e5e78ba56be226b70
- https://www.semanticscholar.org/paper/Improving-Community-Detection-Methods-for-Network-Moradi/48ba86a3d99850181ab7e90b3be0a05ae869330e
- https://www.semanticscholar.org/paper/Various-Approaches-of-Community-Detection-in-A-Mahajan-Kaur/5fdc1fbbd2b758bf654a2d5f68e373ddd3604104
- https://www.semanticscholar.org/paper/Community-Detection-in-Multiplex-Networks-Hanteer-Interdonato/9c2915e1fc26025b6099ab9e9dfac2487692e831
- https://www.semanticscholar.org/paper/Detection-and-analysis-of-overlapping-community-for-Shahriari/013835530c6d8426fd340629f1f3d2ae98d3a860

**Comment by DonaldTsang** [comment]
Also to vibe with HKUST, take a look at https://github.com/RapidsAtHKUST/CommunityDetectionCodes

**Comment by GiulioRossetti** [comment]
> Also to vibe with HKUST, take a look at https://github.com/RapidsAtHKUST/CommunityDetectionCodes

Thank's for the resource. 
There are a few python implementations worth considering in the list. 

Our approach is to integrate only algorithms having python implementations (or that are shipped with python bindings - e.g., Leiden, Infomap) so as to maintain CDlib installation easy.

**Comment by BrandonKMLee** [comment]
Another paper that tried to curate CD algos https://www.researchgate.net/publication/295395520_Community_detection_in_social_networks
